### PR TITLE
Mock disabled dependency outputs.

### PR DESCRIPTION
**Pull request by jlepere-everlaw**
## Description

Fixes https://github.com/gruntwork-io/terragrunt/issues/2734.

Previously, using disabled dependency outputs wasn't really working because it would require that the `terragrunt.hcl` file as present, which was a bug. Additionally, disabled dependencies didn't have mocked outputs loaded, which doesn't really make sense otherwise.

## Release Notes (draft)

Updated disabled dependencies to properly use mocked outputs.

### Migration Guide

n/a

### CODE REVIEW

**Comment by jlepere-everlaw** [comment]
I've tested this by ensuring it solves problems I've been seeing, describe in more detail in https://github.com/gruntwork-io/terragrunt/issues/2734#issuecomment-1834320936, following the [docs](https://github.com/gruntwork-io/terragrunt/issues/2734#issuecomment-1834320936) to run `terragrunt` locally.

**Comment by denis256** [comment]
Failing test `TestTerragruntDisabledDependency`

**Comment by denis256** [comment]
Also will be helpful to have integration tests that will track that disabled modules work as expected

**Comment by jlepere-everlaw** [comment]
> Failing test `TestTerragruntDisabledDependency`
> Also will be helpful to have integration tests that will track that disabled modules work as expected

Agh, I'm struggling a bit to fix/update this. Can you help?

**Comment by yhakbar** [comment]
Hey @jlepere-everlaw 

Sorry we let this PR go stale. I recognize that this isn't the first PR you've opened that we've let go stale, and it sucks that this has been your experience trying to contribute to Terragrunt. We want it to be a smoother experience, and we're working on some improvements to make it so.

Are you able to run the test `TestTerragruntDisabledDependency` locally? This is one example of how you would do that:

```bash
❯ go test -run 'TestTerragruntDisabledDependency' test/integration_test.go test/integration_debug_test.go test/integration_common_test.go
ok  	command-line-arguments	0.725s
```

I ran that locally without using any AWS credentials, etc. We have plans to make this a simpler process, but this should help you overcome that bug.

I'll leave this PR open for another week if you'd like to work on it, then we'll revisit if it's still stale.

**Comment by jlepere-everlaw** [comment]
Thanks, @yhakbar. I'm a bit swamped atm so won't be able to get to this anytime soon, so I'll go ahead and close this.

**Pull request closed without merging**
