### PR TITLE
Improve partial parsing HCL strings by adding cache

### LINKED ISSUE #2203: Improve partial parsing HCL strings by adding cache
### Motivation
As outlined in #1971 my customer still has issues with the parsing time of the later Terragrunt versions since 0.32. Still there is a requirement for my team to get a new version of Terraform and Terragrunt working ASAP. So @nilreml and I took some time to understand the Terragrunt code better and find a potential solution to our issue.
To get this straight: We are working on a big project containing ~150 AWS accounts, 6 environments and ~75 Terraform modules. The Terragrunt code is sometimes very complex containing multiple dependency layers. We already took the time to optimize and review all of the `*.hcl` files to reduce `includes/read_terragrunt_config` calls, calls to other custom functions and simplifying logic of loops. Still we only get minor improvements in our parsing times (time until all dependencies are resolved and Terraform is triggered the first time).

After the merge of #2010 and the 0.36.6 release another colleague of mine did some re-measuring of execution times in our environment:

| tg version | init 1 | init 2 | init 3 | plan 1 | avg | factor to 0.29.2 |
|------------|-------|-------|-------|--------|-----|------------------|
| 0.29.2 parsing | 0:01:11 | 0:00:50 | 0:01:14 | 0:01:02 | 64s | 1.0 |
| 0.29.2 complete | 0:04:11 | 0:04:32 | 0:04:13 | 0:04:14 | 257s | 1.0 |
| 0.33.2 parsing | 0:01:15 | 0:01:44 | -  | -  | 127s | 2.0 |
| 0.33.2 complete | 0:05:48 | 0:07:34 | -  | -  | 401s | 1.6 |
| 0.34.3 parsing | 0:05:54 | 0:05:21 | -  | -  | 337s | 5.3 |
| 0.34.3 complete | 0:24:59 | 0:21:02 | -  | -  | 1381s | 5.4 |
| 0.35.20 parsing | 0:04:50 | 0:04:34 | -  | -  | 282s | 4.4 |
| 0.35.20 complete | 0:23:39 | 0:23:14 | -  | -  | 1406s | 5.4 |
| 0.36.3 parsing | 0:04:23 | 0:04:44 | -  | -  | 274s | 4.3 |
| 0.36.3 complete | 0:24:26 | 0:21:57 | -  | -  | 1391s | 5.4 |
| 0.36.6 parsing | 0:01:16 | 0:02:09 | 0:01:52 | 0:02:11 | 112s | 1.8 |
| 0.36.6 complete | 0:07:26 | 0:11:29 | 0:07:31 | 0:08:54 | 530s | 2.1 |

Unfortunately i don't know his testing method, but i can confirm that times are still high.

As you can see, there is a gap between 0.29 and 0.33 (0.32 to be precise) which the 0.36 version was unable to fix. So we did some code crawling on that version to see where the "evil code" was introduces and found [changes between 0.31 and 0.32](https://github.com/gruntwork-io/terragrunt/compare/v0.31.11...v0.32.6) to be the culprit.

To be super sure on this we created flamegraphs for the the versions in question:

- v31 [pprof.terragrunt_dirty_31.samples.cpu.001.pb.gz | flamegraph.com](https://flamegraph.com/share/55d04ab8-c9e6-11ec-be1a-eee422b1bda9)
- v32 [pprof.terragrunt_dirty_32.samples.cpu.001.pb.gz | flamegraph.com](https://flamegraph.com/share/5e6d362a-c9e6-11ec-be1a-eee422b1bda9)
- v36 [pprof.terragrunt_dirty_36.samples.cpu.001.pb.gz | flamegraph.com](https://flamegraph.com/share/6be11772-c9e6-11ec-be1a-eee422b1bda9)

Those flamegraphs have a hacked in pprof and were recompiled by me from their latest tag on git. Those profiles have been gathered during a `terragrunt run-all init` run.

### Rationale
(Note: The sections below may mix up the functionality of `include` and `dependency`, however, every dependency will cause an implicit include due to required parsing of the dependencies.)

Due to introduction of multiple includes in 0.32 (presumably #1804) we found that the stack sizes between 0.31 and 0.32 drastically changed. This makes sense in general so Terragrunt would now parse includes multiple times and do another step of marshaling and unmarshaling HCL with JSON due to typing conflicts with `cty` in decode sections - at least from what we understood. Even though we cannot pin those changes to the `PartialParseConfig` calls, we saw at least increased calls to `DecodeBaseBlocks` which is called from `PartialParseConfig`. Also it could be related to changes in `configFileHasDependencyBlock`.

Our project makes use of a deep variable hierarchy using `.hcl` files, causing repeated parsing of `.hcl` files over and over for each module, in addition to the usual root `terragrunth.hcl`.
Also, our project has hundreds of module instances using `terragrunt.hcl` files via symbolic links.

Revisiting the changes of the `setIAMRole` function in `config.go` (#2010), we considered adding a cache/memoization to either `DecodeBaseBlocks` or `PartialParseConfigString`. We already knew that we can cache `PartialParseConfigString` just as `setIamRole` does, so this is our preferred option.

Comparing performance:

| - |  Best case | Average case | Worst case |
| --- | --- | --- | --- |
| Regular implementation of partial parsing | O(1) | O(n) | O(n^2) |
| Cached implementation | O(1) | O(n) | O(n) |

With `n` being number of iterations for parsing dependencies/includes.

As of now we are not aware of any Terragrunt features the cause side-effects on `PartialParseConfigString` except for the already discussed `setIAMRole`.

### Doing
To prove our points we did an initial implementation reusing the code of `cache.go` which was implemented for the `setIAMRole` feature. A switch was added to run the compiled version with and without caching behavior.
Additionally, two fixtures and two benchmarks were written to have a reproducible use cases.

The PR will follow up on this issue.

Please let's discuss your thoughts on our observations and suggested mitigation.

This story was co-created by @nilreml.

### PR DESCRIPTION
**Pull request by maunzCache**
## Description

Fixes #2203.

This PR will add a caching behavior to `PartialParseConfigString` in `config.go`. The original function has been wrapped by a new function called `TerragruntConfigFromPartialConfigString` which handles cache access if the flag `--terragrunt-use-partial-parse-config-cache` was provided.

This fix was co-authored by @nilreml.

We are very open to suggestions or objections of this PR. If you find anything that we overlooked, please speak out.

### Technical subtleties

The implementation uses the same approach as the `setIAMRole` cache in `config.go` (#2010) but drops the additional hashing of the key used in the cache map. We decided to drop this as our understanding is that this interferes with the native behavior of go maps. Go implements the map type as hashmap which already handles uniqueness and collisions by providing a cache bucket implementation. See [the docs and implementation](https://github.com/golang/go/blob/master/src/runtime/map.go) for reference. 

### Testing
As we have no concrete unit test for this implementation besides verifying that our cache works in general, we decided to add two fixtures.

The fixtures are very similar: Both implement dependencies and require heavy parsing due to massive stub data. The first variant implements includes by creating locals which call `read_terragrunt_config`. The second implements the multi-include approach which was implemented in 0.32.
Both fixtures are used in [benchmark tests](https://pkg.go.dev/testing#hdr-Benchmarks) to verify the impact of the implementation.

One benchmark has been implemented for the execution of `runGraphDependencies` which is the fastest functionality that accesses `PartialParseConfigString` and could additionally be used to verify if dependency order is correct even after enabling the cache. The second benchmark was implemented for `ReadTerragruntConfig` as this will call all subsequent functionality which is necessary for parsing. Each benchmark consists of one of the fixtures plus the caching enabled or disabled.

The benchmarks verify that CPU and memory usage don't change drastically when using the cache. However, for huge projects which surely exceed the fixture, use cases should be considered to implement a cache invalidation to prevent out of memory errors.

We realize the limited benefits since this project doesn't make use of benchmarks yet and may have to decide on how to handle them. We suggest implementing least a benchmark call in the CI/CD pipeline which is executing the unit and integration tests.
For the future all benchmarks should be collected and somehow be compared to easily find regressions if features are added or changed. [This blog post](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) might help with an implementation.

It has to be noted that benchmark tests are not representative but validate our use case.

### Implementation notes

During our implementation we couldn't find an answer to the following questions:

1. Was a side effect created for `setIamRole`?
2. Have the `.terragrunt-cache/` directories which are created during the benchmark test to be removed or not?

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Add caching to `PartialParseConfigString` which can be activated via `--terragrunt-use-partial-parse-config-cache`.

### Migration Guide

Nothing to do.

### CODE REVIEW

**Comment by maunzCache** [comment]
Improvements in our scenario

**Parsing times - terragrunt init on WSL**

| scope                     | 0.29.11 | caching (0.38.4) |
| ------------------------- | ------- | ---------------- |
| dev2/hub                  |   00:23 |            00:10 |
| dev2/spoke/account-dev2-b |   00:11 |            00:05 |
| dev2/spoke                |   00:19 |            00:07 |
| dev2                      |   00:27 |            00:10 |
| prod/hub                  |   03:49 |            00:14 |
| prod/spoke                |   12:13 |            00:07 |
| prod                      |   07:21 |            00:07 |
| shared                    |   00:20 |            00:09 |
| test/hub                  |   00:26 |            00:11 |
| test/spoke                |   00:42 |            00:07 |
| test                      |   00:45 |            00:12 |
| cicd                      |   00:22 |            00:12 |

**Parsing times - terragrunt init on EC2 c5.4xlarge**

| scope                     | 0.29.11 | caching (0.38.4) |
| ------------------------- | ------- | ---------------- |
| dev2/hub                  |   00:27 |            00:11 |
| dev2/spoke/account-dev2-b |   00:13 |            00:07 |
| dev2/spoke                |   00:23 |            00:08 |
| dev2                      |   00:30 |            00:12 |
| prod/hub                  |   04:06 |            00:15 |
| prod/spoke                |   12:34 |            00:08 |
| prod                      |   08:05 |            00:16 |
| shared                    |   00:23 |            00:10 |
| test/hub                  |   00:29 |            00:13 |
| test/spoke                |   00:48 |            00:08 |
| test                      |   00:57 |            00:13 |
| cicd                      |   00:26 |            00:11 |

**Comment by nilreml** [comment]
Small note about the hashing:
Using a hash function on the cache key in the manner done by `setIAMRole` in `config.go` is indeed prone to unmitigated collisions of the hash function, potentially leading to incorrect results.
I'd suggest fixing it in `setIAMRole` as well - let us know and we'll add the fix to this PR.

**Comment by maunzCache** [comment]
Only resolved the merge conflict via github editor. Does seem to create side effects for the unit tests. Will pull locally and check the broken unit tests. Guess it is formatting related.

**Comment by denis256** [comment]
```
Terraform fmt............................................................Passed
goimports................................................................Failed
- hook id: goimports
- files were modified by this hook

options/options.g
```

**Comment by maunzCache** [comment]
Was just an additional newline. Fixed and pushed. pre-commit had no further issues on my system

**Comment by maunzCache** [comment]
As i'll leave the customer project @nilreml may take over if there is any changes required for the PR.,

**Comment by maunzCache** [comment]
Any chance to get endorsement for this feature?

**Comment by maunzCache** [comment]
@yorinasub17 @zackproser @rhoboat @denis256 Do you have an ETA for me when this gets a chance for a review?

**Comment by denis256** [comment]
Changes LGTM to me

**Review by denis256 — APPROVED** [review]

**Comment by martin566** [comment]
@denis256: Thanks for approving this pull-request.

**Comment by nilreml** [comment]
Thanks a bunch for merging and releasing this :+1:

**Pull request merged**
