### PR TITLE
Fixing running pseudo-tty commands

### LINKED ISSUE #3507: terragrunt console broken
## Describe the bug

terragrunt console has stopped working since commit afd5d7f962bd1e651f04a44968342ed1642a8e8e. Release v0.68.0-beta2024100702 is the latest working version.

## Steps To Reproduce

Run terragrunt console on Linux/macOS

```
$ terragrunt §
17:39:36.859 DEBUG  Terragrunt Version: 0.68.4
17:39:36.862 DEBUG  Did not find any locals block: skipping evaluation.
17:39:36.863 DEBUG  Running command: terraform --version
17:39:36.863 DEBUG  Engine is not enabled, running command directly in .
17:39:36.909 DEBUG  terraform version: 1.8.5
17:39:36.910 DEBUG  Reading Terragrunt config file at ./terragrunt.hcl
17:39:36.911 DEBUG  Did not find any locals block: skipping evaluation.
17:39:36.913 DEBUG  Did not find any locals block: skipping evaluation.
17:39:36.916 DEBUG  terraform files in ./.terragrunt-cache/RNJ0idZ78sgcGuo079PsS-TYfWQ/ThyYwttwki6d6AS3aD5OwoyqIWA are up to date. Will not download again.
17:39:36.916 DEBUG  Copying files from . into ./.terragrunt-cache/RNJ0idZ78sgcGuo079PsS-TYfWQ/ThyYwttwki6d6AS3aD5OwoyqIWA
17:39:37.199 DEBUG  Setting working directory to ./.terragrunt-cache/RNJ0idZ78sgcGuo079PsS-TYfWQ/ThyYwttwki6d6AS3aD5OwoyqIWA
17:39:37.199 DEBUG  The file path ./.terragrunt-cache/RNJ0idZ78sgcGuo079PsS-TYfWQ/ThyYwttwki6d6AS3aD5OwoyqIWA/provider.tf already exists, but was a previously generated file by terragrunt. Since if_exists for code generation is set to "overwrite_terragrunt", regenerating file.
17:39:37.202 DEBUG  Generated file ./.terragrunt-cache/RNJ0idZ78sgcGuo079PsS-TYfWQ/ThyYwttwki6d6AS3aD5OwoyqIWA/provider.tf.
17:39:37.239 DEBUG  Running command: terraform console
17:39:37.239 DEBUG  Engine is not enabled, running command directly in ./.terragrunt-cache/RNJ0idZ78sgcGuo079PsS-TYfWQ/ThyYwttwki6d6AS3aD5OwoyqIWA
17:39:37.240 ERROR  Error closing pty: invalid argument
17:39:37.240 ERROR  terraform invocation failed in ./.terragrunt-cache/RNJ0idZ78sgcGuo079PsS-TYfWQ/ThyYwttwki6d6AS3aD5OwoyqIWA
17:39:37.241 ERROR  error occurred:

* Failed to execute "terraform console" in ./.terragrunt-cache/RNJ0idZ78sgcGuo079PsS-TYfWQ/ThyYwttwki6d6AS3aD5OwoyqIWA

  fork/exec /usr/bin/terraform: operation not permitted

17:39:37.241 DEBUG  *fs.PathError fork/exec /usr/bin/terraform: operation not permitted
/home/circleci/project/internal/os/exec/ptty_unix.go:40 (0x1510f2c)
/home/circleci/project/internal/os/exec/cmd.go:61 (0x1510387)
/home/circleci/project/shell/run_shell_cmd.go:193 (0x16a9715)
/home/circleci/project/telemetry/metrics.go:42 (0xaaf473)
/home/circleci/project/telemetry/telemetry.go:80 (0x16a80cd)
/home/circleci/project/telemetry/traces.go:38 (0xab1e0f)
/home/circleci/project/telemetry/telemetry.go:79 (0x16a7fc9)
/home/circleci/project/shell/run_shell_cmd.go:111 (0x16a7c4b)
/home/circleci/project/shell/run_shell_cmd.go:72 (0x16a7b05)
/home/circleci/project/cli/commands/terraform/action.go:457 (0x1bc73c9)
/home/circleci/project/cli/commands/terraform/action.go:327 (0x1bc66dc)
/home/circleci/project/cli/commands/terraform/action.go:419 (0x1bc6f0c)
/home/circleci/project/cli/commands/terraform/action.go:326 (0x1bc62ce)
/home/circleci/project/cli/commands/terraform/action.go:237 (0x1bc58c7)
/home/circleci/project/cli/commands/terraform/action.go:83 (0x1bc4b32)
/home/circleci/project/cli/commands/terraform/command.go:47 (0x22cf505)
/home/circleci/project/cli/app.go:235 (0x22d0f47)
/home/circleci/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 (0x165d5d0)
/usr/local/go/src/runtime/asm_amd64.s:1700 (0x477c21)

17:39:37.241 ERROR  Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

## Versions

* Terragrunt version: 0.68.4
* OpenTofu/Terraform version: 1.8.5

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

Fixes #3507.

The PR also fixed the error message `error forwarding stdin: write /dev/ptmx: input/output error` that was always displayed when exiting the console.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### CODE REVIEW

**Comment by denis256** [comment]
Can a test be added to ensure this issue does not happen again?

**Comment by levkohimins** [comment]
> Can a test be added to ensure this issue does not happen again?

I tried to add an integration test but couldn't find a way to interact with stdin through the cli package. If you have any suggestions, I'd like to consider them.

**Review by denis256 — APPROVED** [review]
This could potentially be a separate CircleCI job to run the compiled executable in various scenarios. However, I believe that might fall outside the scope of this PR.

**Comment by levkohimins** [comment]
> This could potentially be a separate CircleCI job to run the compiled executable in various scenarios. However, I believe that might fall outside the scope of this PR.

I created an issue #3521

**Pull request merged**
