### PR TITLE
[IAC-1677] Replace gofmt with goimports

### PR DESCRIPTION
**Pull request by ina-stoyanova**
Replace gofmt with goimports in the pre-commit configuration. Note: This PR was opened using git-xargs.

### CODE REVIEW

**Comment by zackproser** [comment]
This one seems to be failing due to `go.sum` [mismatches](https://app.circleci.com/pipelines/github/gruntwork-io/terragrunt/867/workflows/e1f61c5e-1926-4f38-af63-1a4ce920a0d6/jobs/6946) which should be fixable by running all the specified `go get` commands perhaps followed by `go mod tidy`.

**Comment by ina-stoyanova** [comment]
Thanks, Zack - giving this a go now :)

**Comment by ina-stoyanova** [comment]
I don't know why this keeps failing - I addresses the missing variables and ran `go mod tidy`.... I feel uncomfortable publishing it if we've got failing tests all unexpectedly.

**Comment by ina-stoyanova** [comment]
Merging with master now, and let's see where the tests land.

**Comment by ina-stoyanova** [comment]
wohoo! 🎉  can I get a stamp of approval here :)

**Review by marinalimeira — APPROVED** [review]
LGTM

**Pull request merged**
