### PR TITLE
Have test case for showing that plan-all swallows error messages

### PR DESCRIPTION
**Pull request by jmahowald**
When running terragrunt plan-all any errors in terraform are swallowed.  This is in contrast to running terraform plan in the offending subdir.  

This pull doesn't actually fix the behavior, but does add an integration test to demonstrate the issue.  Do you agree that this is change worth pursuing?  If so, any tips on where best to look to make the more specific change would be appreciated.

### CODE REVIEW

**Comment by brikis98** [comment]
Ooh, nice, love the TDD! 

Definitely worth fixing. Looks like #251 mentioned the same thing. #74 also mentions the need to save those logs to file, as reading them all in the console for a large number of modules being deployed in parallel is overwhelming.

I'm not sure where the bug is. Some likely starting points:

* There is logic here to capture error streams and summarize them: https://github.com/gruntwork-io/terragrunt/blob/master/configstack/stack.go#L33-L38. Probably something is broken with this logic here.

* Modules are executed here: https://github.com/gruntwork-io/terragrunt/blob/master/configstack/running_module.go#L187

* `TerragruntOptions`, which contains the logger, is cloned here: https://github.com/gruntwork-io/terragrunt/blob/master/configstack/module.go#L81

**Comment by jmahowald** [comment]
I like the idea of having distinct files for the different streams, and I think I know how it could be tackled now, but this fix is a fair amount easier. There was just an if condition that resulted in errors not being printed if there was a very particular error message.

**Comment by brikis98** [comment]
Ah, that fix makes sense. Do all the tests pass now?

**Comment by jmahowald** [comment]
All the other tests pass.  Not the new one I created though.  Something about how stderr + logger are interacting in the tests that I haven't fully worked out yet.  I'll have to punt a bit on that part for now, but will hopefully get back to that this week.

**Comment by jmahowald** [comment]
@brikis98 I would love to get this merged in before I start having more people using terragrunt , but the fact that my added test failed is preventing me from doing so in good conscience.  The problem is that I spent a couple of hours trying to manipulate stdout/stderr from the tests and just had to throw up my hands.  Is there another way of verifying this behavior, or perhaps you fixed it in another way (the part where plan-all would swallow error messages).

**Comment by brikis98** [comment]
```go
output := stdout.String()
errOutput := stderr.String()
```

What do those contain when you run your new test?

**Comment by jmahowald** [comment]
See output here
https://asciinema.org/a/xscN5iWx8Rcr1VNujBPtKRR4v

**Comment by brikis98** [comment]
> See output here https://asciinema.org/a/xscN5iWx8Rcr1VNujBPtKRR4v

Hm, the stdout/stderr flashes by before I can actually see it in that video. Could you paste it into a [GitHub gist](https://gist.github.com)?

**Comment by jmahowald** [comment]
https://gist.github.com/jmahowald/1431cc274ad982ad005c0ae9c0f626cb
It's the capturing of stderr in the test that is not working correctly.

**Comment by brikis98** [comment]
Ah, I see. I *think* what might be happening is that `TerragruntOptions` sets its `Logger` field via a call to `util.CreateLogger` [here](https://github.com/gruntwork-io/terragrunt/blob/master/options/options.go#L98) and [here](https://github.com/gruntwork-io/terragrunt/blob/master/options/options.go#L134). The [CreateLogger](https://github.com/gruntwork-io/terragrunt/blob/master/util/logger.go#L14) function always logs to `os.Stderr`, rather than whatever other `Writer` you may have specified. I think you fix that method to take in a `Writer` and set it to `TerragruntOptions.ErrWriter`, you'll be all set.

**Comment by jmahowald** [comment]
Thanks.  I had updated the Clone method and added in a CreateLoggerWithWriter function it was using.
I've checked that in, along with some other parts I can back out of when it's all working.

Still no dice, as I'm not sure how to get it in during the New call.  I'm not yet seeing the relationship between the App which does get an errWriter and the TerragruntOptions, but I'm suspecting that if I can figure that out/ a way to pass that errWriter into the options creation that it would be good.

Thanks

**Comment by brikis98** [comment]
Looks like you're on the right track! Note my original message:

> Ah, I see. I *think* what might be happening is that `TerragruntOptions` sets its `Logger` field via a call to `util.CreateLogger` [here](https://github.com/gruntwork-io/terragrunt/blob/master/options/options.go#L98) and [here](https://github.com/gruntwork-io/terragrunt/blob/master/options/options.go#L134).

I think you only updated one of those two locations with your new `CreateLoggerWithWriter` function!

**Comment by jmahowald** [comment]
All clear now.  Thanks for al the help (and the great tool)

**Comment by jmahowald** [comment]
Removed the binary, there is one in master though BTW.

I had indeed missed a test, but have fixed with one more minor refactoring.  All tests now pass.

```
$ go test ./...
?       github.com/gruntwork-io/terragrunt      [no test files]
?       github.com/gruntwork-io/terragrunt/aws_helper   [no test files]
ok      github.com/gruntwork-io/terragrunt/cli  12.991s
ok      github.com/gruntwork-io/terragrunt/config       0.023s
ok      github.com/gruntwork-io/terragrunt/configstack  0.028s
ok      github.com/gruntwork-io/terragrunt/dynamodb     21.271s
?       github.com/gruntwork-io/terragrunt/errors       [no test files]
?       github.com/gruntwork-io/terragrunt/options      [no test files]
ok      github.com/gruntwork-io/terragrunt/remote       0.018s
ok      github.com/gruntwork-io/terragrunt/shell        6.555s
ok      github.com/gruntwork-io/terragrunt/test 185.592s
?       github.com/gruntwork-io/terragrunt/test/helpers [no test files]
ok      github.com/gruntwork-io/terragrunt/util 0.020s
```

**Comment by brikis98** [comment]
> Removed the binary, there is one in master though BTW.

Huh. So there is. Not sure when that happened, but thanks :)

> I had indeed missed a test, but have fixed with one more minor refactoring. All tests now pass.

Fantastic. Thank you! Merging now.

**Comment by jmahowald** [comment]
@brikis98 Can you let me know when your next planned release is?  Trying to decide how much to jerry-rig in terms of creating my own build for our workstation pipeline.  If it's days, probably not, if it's weeks maybe so

Thanks

**Comment by brikis98** [comment]
That's totally my bad. I meant to release this immediately, but just lost track of it. New release here: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.13.3

**Comment by brikis98** [comment]
(binaries are building now)

**Pull request merged**
