### PR TITLE
Add access logging permissions

### PR DESCRIPTION
**Pull request by brikis98**
This is a follow-up to #645. The tests were failing with the error:

```
InvalidTargetBucketForLogging: You must give the log-delivery group WRITE and READ_ACP permissions to the target bucket
```

This PR is an attempt to grant those permissions.

### CODE REVIEW

**Comment by Xtigyro** [comment]
@brikis98 Can I assist in any way?

**Comment by brikis98** [comment]
@Xtigyro Thanks, but I _think_ this PR fixes the issue, but I'm hitting some other, perhaps unrelated test failures. Will look into it tomorrow or day after, time permitting.

**Comment by brikis98** [comment]
OK, the tests were failing due to an unrelated issue, but still a bug: when processing include/exclude arguments for `xxx-all` commands, we were iterating over a map, and in Go, map iteration order is random. So sometimes we'd process includes one way and sometimes another. This caused the tests to fail, but more importantly, it meant that real-world behavior could be inconsistent too. I've fixed it so we use a consistent sort order now and the tests are passing. Merging!

**Comment by Xtigyro** [comment]
@brikis98 Very nice!

**Pull request merged**
