### PR TITLE
Handle the merge of error hooks

### PR DESCRIPTION
**Pull request by smitthakkar96**
The previous PR got merged without this commit

This PR builds on the PR #1967, which adds Error Hooks.

### CODE REVIEW

**Comment by smitthakkar96** [comment]
@yorinasub17 @rhoboat the pervious PR was missing the merge part that @yorinasub17 pointed out

**Comment by rhoboat** [comment]
Running tests on this PR now. This time. 😅  I'm learning!

**Comment by smitthakkar96** [comment]
```
Terraform fmt............................................................Passed
goimports................................................................Failed
- hook id: goimports
- files were modified by this hook

test/integration_test.go
test/integration_test.go
test/integration_test.go
test/integration_test.go
test/integration_test.go

```

**Comment by smitthakkar96** [comment]
I will push a fix

**Comment by rhoboat** [comment]
@smitthakkar96 Also please merge or rebase on master, which has the fix from #1980.

**Comment by smitthakkar96** [comment]
@rhoboat can you run the build. I also rebased and fix the pre-commit errors

**Comment by rhoboat** [comment]
Are you sure you rebased/merged with master? I don't see the included change to `test/integration_test.go`.

**Comment by smitthakkar96** [comment]
Screenshot 2022-01-14 at 18 16 32

This is what I see when I do `git log` @rhoboat

**Comment by smitthakkar96** [comment]
Screenshot 2022-01-14 at 18 18 28

I can even see the change maybe something up with github

**Review by rhoboat — APPROVED** [review]
LGTM, and tests passed on a version of this branch that includes the changes from #1980, (For ref: [comparison](https://github.com/gruntwork-io/terragrunt/compare/smit/merge_error_hooks) | [commit](https://github.com/gruntwork-io/terragrunt/commit/7c0d8a88ac87c8b48ea892b05976b0577bf172bc))

**Comment by rhoboat** [comment]
Thanks @smitthakkar96 for your contributions and for sticking this through!

**Comment by smitthakkar96** [comment]
No problem! Thanks for quick and detailed feedback and helping to merge `error_hooks` :)

I was interested in creating the RFC as we were discussing in the previous PR regarding lexical ordering of hooks. Can I go ahead?

**Pull request merged**
