### PR TITLE
#1904 Added protection check for "apply -destroy" invocation

### PR DESCRIPTION
**Pull request by denis256**
Added protection check for "apply -destroy" invocation

Fix for: https://github.com/gruntwork-io/terragrunt/issues/1904

### CODE REVIEW

**Review by yorinasub17 — DISMISSED** [review]
LGTM! Let me kick off the build, and if it passes, we can merge this in!

**Comment by yorinasub17** [comment]
Looks like the build failed the new test `TestPreventDestroyApply`:

https://app.circleci.com/pipelines/github/gruntwork-io/terragrunt/1157/workflows/85161ca5-380e-4df9-a7b1-dbcf5064c828/jobs/8013

**Comment by denis256** [comment]
Updated test to copy work directory to a temporary location, sharing same fixture directory between tests and run destroy wasn't a good idea

**Review by yorinasub17 — APPROVED** [review]
Update LGTM and test passed so going to merge this in!

**Pull request merged**
