### PR TITLE
Restore IsRemote() check when comparing backend

### LINKED ISSUE #316: Crash: "runtime error: invalid memory address or nil pointer dereference"
What is happening here? First of all, my S3 state has not changed. Then, it tries to import it and crashes! :(

terragrunt version v0.13.7
Terraform v0.10.7

```
doug@ADMINs-MacBook-Pro-2 widgetcorp (master) [widgetcorp_eu] $ tg apply --var-file ~/tfvars/widgetcorp.tfvars
[terragrunt] [/Users/doug/git/terraform/terraform-live/terragrunt/eu-central-1/euprod/widgetcorp] 2017/10/12 08:32:09 Running command: terraform --version
[terragrunt] 2017/10/12 08:32:09 Reading Terragrunt config file at /Users/doug/git/terraform/terraform-live/terragrunt/eu-central-1/euprod/widgetcorp/terraform.tfvars
[terragrunt] 2017/10/12 08:32:09 WARNING: no double-slash (//) found in source URL /Users/doug/git/terraform/terraform-modules/widgetcorp. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2017/10/12 08:32:09 Cleaning up existing *.tf files in /var/folders/jr/b3nl0vcj7hgclvbfbt2mdrhw0000gp/T/terragrunt/FUYc4vvbbeeAusv9CM_VpOpxY0M/TcDLwgb-0LmdbdvcWfM7FNWB6UM
[terragrunt] 2017/10/12 08:32:09 Downloading Terraform configurations from file:///Users/doug/git/terraform/terraform-modules/widgetcorp into /var/folders/jr/b3nl0vcj7hgclvbfbt2mdrhw0000gp/T/terragrunt/FUYc4vvbbeeAusv9CM_VpOpxY0M/TcDLwgb-0LmdbdvcWfM7FNWB6UM using terraform init
[terragrunt] [/Users/doug/git/terraform/terraform-live/terragrunt/eu-central-1/euprod/widgetcorp] 2017/10/12 08:32:09 Backend s3 has not changed.
[terragrunt] [/Users/doug/git/terraform/terraform-live/terragrunt/eu-central-1/euprod/widgetcorp] 2017/10/12 08:32:09 Running command: terraform init -backend-config=bucket=sws-tfstate -backend-config=key=widgetcorp/terraform.tfstate -backend-config=region=us-west-1 -backend-config=encrypt=true -from-module=file:///Users/douglasgarstang/git/terraform/terraform-modules/widgetcorp /var/folders/jr/b3nl0vcj7hgclvbfbt2mdrhw0000gp/T/terragrunt/FUYc4vvbbeeAusv9CM_VpOpxY0M/TcDLwgb-0LmdbdvcWfM7FNWB6UM
Copying configuration from "file:///Users/doug/git/terraform/terraform-modules/widgetcorp"...
Downloading modules...
Do you want to copy the state from "s3"?
  Terraform has detected you're unconfiguring your previously set backend.
  Would you like to copy the state from "s3" to local state? Please answer
  "yes" or "no". If you answer "no", you will start with a blank local state.

  Enter a value: yes

Do you want to copy state from "s3" to "local"?
  Pre-existing state was found in "s3" while migrating to "local". No existing
  state was found in "local". Do you want to copy the state from "s3" to
  "local"? Enter "yes" to copy and "no" to start with an empty state.

  Enter a value: yes



Successfully unset the backend "s3". Terraform will now operate locally.

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.template: version = "~> 1.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
[terragrunt] 2017/10/12 08:32:56 Copying files from /Users/doug/git/terraform/terraform-live/terragrunt/eu-central-1/euprod/widgetcorp into /var/folders/jr/b3nl0vcj7hgclvbfbt2mdrhw0000gp/T/terragrunt/FUYc4vvbbeeAusv9CM_VpOpxY0M/TcDLwgb-0LmdbdvcWfM7FNWB6UM
[terragrunt] 2017/10/12 08:32:56 Setting working directory to /var/folders/jr/b3nl0vcj7hgclvbfbt2mdrhw0000gp/T/terragrunt/FUYc4vvbbeeAusv9CM_VpOpxY0M/TcDLwgb-0LmdbdvcWfM7FNWB6UM
[terragrunt] 2017/10/12 08:32:56 runtime error: invalid memory address or nil pointer dereference
[terragrunt] 2017/10/12 08:32:56 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

### PR DESCRIPTION
**Pull request by TimJones**
Fixes #316

### CODE REVIEW

**Comment by brikis98** [comment]
Thanks for the PR! The change looks good. Do the tests pass? Unfortunately, we can't run our CI for external PRs automatically due to security concerns.

**Comment by TimJones** [comment]
I just ran the ones for `remote`, but if needed I can run the full test suite...
```cd remote  && go test -v -parallel 128
=== RUN   TestToTerraformInitArgs
=== RUN   TestToTerraformInitArgsNoBackendConfigs
=== RUN   TestDiffersFrom
=== RUN   TestParseTerraformStateLocal
=== RUN   TestParseTerraformStateRemote
=== RUN   TestParseTerraformStateRemoteFull
=== RUN   TestParseTerraformStateEmpty
=== RUN   TestParseTerraformStateInvalid
--- PASS: TestToTerraformInitArgs (0.00s)
--- PASS: TestParseTerraformStateInvalid (0.00s)
--- PASS: TestParseTerraformStateEmpty (0.00s)
--- PASS: TestParseTerraformStateRemoteFull (0.00s)
--- PASS: TestParseTerraformStateRemote (0.00s)
--- PASS: TestParseTerraformStateLocal (0.00s)
--- PASS: TestToTerraformInitArgsNoBackendConfigs (0.00s)
[terragrunt] 2017/11/27 13:02:15 Backend  has not changed.
[terragrunt] 2017/11/27 13:02:15 Backend s3 has not changed.
[terragrunt] 2017/11/27 13:02:15 Backend type has changed from s3 to atlas
[terragrunt] 2017/11/27 13:02:15 Backend s3 has not changed.
[terragrunt] 2017/11/27 13:02:15 Backend config has changed from map[bucket:foo key:bar region:us-east-1] to map[region:us-east-1 bucket:different key:bar]
--- PASS: TestDiffersFrom (0.00s)
PASS
[terragrunt] 2017/11/27 13:02:15 Backend config has changed from map[bucket:foo key:bar region:us-east-1] to map[bucket:foo key:different region:us-east-1]
[terragrunt] 2017/11/27 13:02:15 Backend config has changed from map[bucket:foo key:bar region:us-east-1] to map[bucket:foo key:bar region:different]
ok  	github.com/gruntwork-io/terragrunt/remote	0.007s
```

**Comment by brikis98** [comment]
Could you run all the tests please? It should only take a 1-2 min or so. Thank you!

**Comment by TimJones** [comment]
Do the tests incur a cost for my AWS account? I notice they use DynomoDB and my AWS credentials...

**Comment by brikis98** [comment]
The tests create S3 buckets and DynamoDB tables, write some data to them, and then clean them up again. If you're still eligible for the free tier, this shouldn't cost you anything. If you're not, it'll cost you some fractions of a cent for S3 usage (DynamoDB's always has a free tier, so that still shouldn't cost anything). If you're not comfortable with that, let me know.

**Comment by TimJones** [comment]
I'm having issues running the tests. We use MFA even with AWS-CLI, and setting the environment variables doesn't seem to be enough for the tests. All calls to AWS fail.

**Comment by brikis98** [comment]
Setting env vars correctly with MFA is tricky. We even built a tool for it :-D

Anyways, I'll merge this in and see if the tests pass. Worst case, I'll revert it.

**Comment by brikis98** [comment]
The tests passed. New release is here: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.13.22. The binaries should show up in a few minutes. Thanks again for the fix!

**Comment by TimJones** [comment]
Awesome! Is the MFA CLI tool publicly available?? Sounds useful!

**Comment by brikis98** [comment]
No, it's currently only available for Gruntwork customers.

**Pull request merged**
