### PR TITLE
Please update readme.md

### PR DESCRIPTION
**Pull request by divakardevops**
Raising this pull request as part of https://github.com/gruntwork-io/terragrunt/issues/427. 

Can you please update readme.md with below sections.

1. How and when to use "-auto-approve" option
2. Prerequisite section - To mention about compatible terraform version and other things.

### CODE REVIEW

**Comment by brikis98** [comment]
Hm, looks like perhaps there was some branching issue? It seems like you are working on top of some branch I created in 2016?

**Comment by divakardevops** [comment]
I am new to github. sorry for inconvenience.
In which branch i have to create?

**Comment by brikis98** [comment]
1. Fork this repo
1. Create a branch off master and make your changes
1. Submit a PR with those changes

**Comment by brikis98** [comment]
PR hasn't been updated since 2018 and README has been completely replaced/refactored. Closing.

**Pull request closed without merging**
