### PR TITLE
based on reported issue #2158, removed the trailing slash appended to get_path_to_repo_root()

### LINKED ISSUE #2158: `get_path_to_repo_root()` includes trailing slash unlike other functions
The path returned by `get_path_to_repo_root()` includes a trailing `/` where it looks like all other path functions do not.  When building a `source` based on this, it causes `//` problems.

For instance, using the normal expression like this:
```
source = "${get_path_to_repo_root()}/modules//my-thing"
```
it actually resolves to the path `../..//modules//my-thing`.  This causes the entire repo to get copied as the source.  So, now I have to write my expression as:
```
source = "${get_path_to_repo_root()}modules//my-thing"
```
to get the expected path of `../../modules//my-thing`.

Correcting this will likely cause problems for folks.  Either they lose the `//` they currently expect or their existing expression (like my second example above) is no longer a valid path.

### PR DESCRIPTION
**Pull request by eightseventhreethree**
and updated tests to match

## Description

Fixes #2158.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs. (Docs already show this desired state)
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes
* Removes trailing slash appended to the end of `get_path_to_repo_root()`

Added / Removed / Updated [].

### Migration Guide
* Migration:
  * `source = "${get_path_to_repo_root()}/` -> `source = "${get_path_to_repo_root()}//`

### CODE REVIEW

**Comment by eightseventhreethree** [comment]
@yorinasub17 @zackproser @rhoboat @denis256 Hey, is there anything else required to get this merged?

**Comment by denis256** [comment]
Hi,
I will review soon this PR too

**Comment by eightseventhreethree** [comment]
@denis256 Any updates?

**Comment by jarpoole** [comment]
@denis256 Any updates on this? Just spent a few hours debugging only to eventually discover the issue and related PR are extremely simple which is really disheartening...

**Comment by levkohimins** [comment]
@eightseventhreethree, thanks for the PR! 
I had to create another [PR](https://github.com/gruntwork-io/terragrunt/pull/2719) to improve the integration test since I couldn't change your PR (branch).

**Comment by levkohimins** [comment]
Resolved in [v0.51.1](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.51.1) release.

**Comment by jarpoole** [comment]
Really appreciate you following up! Thanks for all the hard work on this amazing tool 🙂

**Pull request closed without merging**
