### PR TITLE
Update docs with Git + encryption changes

### PR DESCRIPTION
**Pull request by brikis98**
Do Readme Driven Development to flush out the ideas for:
1. Using Git for locking
2. Automatic state management with Git
3. Using KMS for encryption

### CODE REVIEW

**Comment by brikis98** [comment]
Update: this PR is now very out of date, so it can't be merged as-is. However, the general ideas and discussion over whether Git is a good locking mechanism are still worth considering.

**Comment by mechastorm** [comment]
Any chance this feature can be merged in yet to master after dealing with the conflicts?

**Comment by brikis98** [comment]
This PR was just put up for discussion. It has not actually been implemented. Comments and feedback welcome :)

**Comment by robkinyon** [comment]
I'm confused - why would KMS encryption only be usable with the Git backend? There's no discussion why I wouldn't be able to use KMS encryption with the S3 backend.

**Comment by brikis98** [comment]
> There's no discussion why I wouldn't be able to use KMS encryption with the S3 backend.

The S3 backend already has encryption if you set the `encrypt` config to true.

**Comment by brikis98** [comment]
Since Terraform now natively supports locking, no longer keeps a local cache of the tfstate file, and has more plans related to security on the horizon, going forward with the plan in this PR makes no sense, so I'm going to close it.

**Pull request closed without merging**
