### PR TITLE
#1457 Detection of duplicated "generate" blocks in HCL files

### PR DESCRIPTION
**Pull request by denis256**
Updated `Terragrunt` to detect generate blocks with duplicate name, fix for issue https://github.com/gruntwork-io/terragrunt/issues/1457

Example:
```
$ cat terragrunt.hcl
generate "backend" {
  path = "data.txt"
  if_exists = "overwrite"
  contents = "test data1"
}
generate "backend2" {
  path = "data2.txt"
  if_exists = "overwrite"
  contents = "test data2"
}
generate "backend" {
  path = "data.txt"
  if_exists = "overwrite"
  contents = "test data11"
}
generate "backend2" {
  path = "data2.txt"
  if_exists = "overwrite"
  contents = "test data22"
}

generate "backend3" {
  path = "data3.txt"
  if_exists = "overwrite"
  contents = "test data3"
}

$ terragrunt init
ERRO[0000] Detected generate blocks with the same name: [backend backend2] 
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1 

```
Included changes:
 * configuration loading updates
 * integration tests to cover this case

### CODE REVIEW

**Review by brikis98 — APPROVED** [review]
LGTM, thank you! I'll kick off tests now.

**Comment by brikis98** [comment]
Ah, tests failed, but it's because of an unrelated bug where the test cases can't handle branch names with slashes in them: https://github.com/gruntwork-io/terragrunt/issues/1778. @denis256 Would you mind fixing that one first in a separate PR? Once that's resolved, we can pull `master` into your several other PRs and see if that gets the tests to pass. Thanks!

**Comment by brikis98** [comment]
OK, https://github.com/gruntwork-io/terragrunt/pull/1799 is now merged. Could you pull in the latest from `master`?

**Comment by denis256** [comment]
Updated with changes from  #1799

**Comment by brikis98** [comment]
Great, thanks! Re-running tests now.

**Review by brikis98 — APPROVED** [review]
Tests passed! Merging now.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.31.9

**Pull request merged**
