### PR TITLE
automatically chomp newlines when using run_cmd

### PR DESCRIPTION
**Pull request by twang817**
It appears that the primary use-case for run_cmd is in file handling.  Most examples I've seen require you to use `echo -n` to make sure newlines are not picked up by terragrunt.

This simply makes Terragrunt chomp any trailing newlines found in the output.

The syntax of run_cmd is already strained at best -- often trying to figure out how to squeeze the `echo -n` is difficult.  You could always factor it out into a script, but having a bunch of loose scripts in the repository -- is less than desirable.

### CODE REVIEW

**Comment by brikis98** [comment]
Thanks for the PR! Code changes look good, but we have to get #466 fixed before merging anything else in, so I'll have to come back to this one. Please rebase on master after #466 is resolved and give us a ping again!

**Comment by tiwood** [comment]
Hi @twang817, @brikis98,
now that #466 is closed, can we revisit this PR? We have many complex run_cmd lines with newline issues and this change would make it much easier for us.

**Review by hougholi — DISMISSED** [review]

**Comment by brikis98** [comment]
I'm not sure if @twang817 is working on this any more, but @tiwood if you want to open up a new PR with these changes, I'd be happy to get it reviewed!

**Comment by twang817** [comment]
Sorry, didn't see a conflict when I saw this notification come through yesterday.  Updated.

**Review by brikis98 — APPROVED** [review]
LGTM! I'll kick off tests now.

**Comment by brikis98** [comment]
Looks like the `go fmt` precommit hook failed. Could you run `go fmt`?

**Comment by kchristensen** [comment]
Any chance of movement on this?

**Comment by yorinasub17** [comment]
Merged and released as https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.7

**Pull request closed without merging**
