### PR TITLE
Bump creack/pty to 1.1.11.

### LINKED ISSUE #1329: [MacOS] terragrunt console - Setctty set but Ctty not valid in child
While trying to invoke the `terraform console` command via `terragrunt console`, 

I get the following error:

```
[terragrunt] 2020/09/07 14:30:52 Running command: terraform console
[terragrunt] 2020/09/07 14:30:52 Error closing pty: invalid argument
[terragrunt] 2020/09/07 14:30:52 Hit multiple errors:
fork/exec /usr/local/bin/terraform: Setctty set but Ctty not valid in child
[terragrunt] 2020/09/07 14:30:52 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

But this seems to work fine on Ubuntu.

---

**Versions:**

```
terragrunt version v0.23.40
Terraform v0.13.2
MacOS Catalina 10.15.6
```

### PR DESCRIPTION
**Pull request by abohne**
Fixes #1329

### CODE REVIEW

**Comment by brikis98** [comment]
Thanks for the PR! Is there something in that new version that explicitly fixes #1329?

**Comment by abohne** [comment]
> Thanks for the PR! Is there something in that new version that explicitly fixes #1329?

There are some details at https://github.com/creack/pty/issues/96#issuecomment-624372400

**Comment by brikis98** [comment]
Ah, understood, thank you! Looks promising. I'll kick off tests now.

**Comment by brikis98** [comment]
Oh, wait, I just realized this PR only updates `go.mod`. There should be an update for `go.sum` too? You may need to run `go mod tidy`.

**Comment by abohne** [comment]
I just ran `go mod tidy` and updated the branch.

**Review by brikis98 — APPROVED** [review]
Thank you! I'll kick off tests now.

**Comment by brikis98** [comment]
Tests passed! Merging now.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.13

**Pull request merged**
