### PR TITLE
locks: add azure_blob lock provider

### PR DESCRIPTION
**Pull request by pmcatominey**
Lock is backed by Azure Blob Storage, a Blob is created with the desired name
to acquire the lock and deleted to release it.

### CODE REVIEW

**Comment by pmcatominey** [comment]
Leasing does not appear to be exposed via the Go SDK so I have raised Azure/azure-sdk-for-go/issues#406. This means that currently the lock is not reliable under concurrently, I'll update this branch when leasing is available.

**Comment by brikis98** [comment]
Exciting to see this PR and potential Azure support! 

> Leasing does not appear to be exposed via the Go SDK so I have raised Azure/azure-sdk-for-go#406. This means that currently the lock is not reliabl concurrently, I'll update this branch when leasing is available.

Ah, that's a shame. Keep us posted!

**Comment by brikis98** [comment]
@pmcatominey Any update on this?

**Comment by ashb** [comment]
The missing feature I think made it into 6.0.0 of the azure SDK: https://github.com/Azure/azure-sdk-for-go/commit/5d83dd9eb7e1440081e0b965d33450961d948188

**Comment by brikis98** [comment]
@ashb Nice find.

@pmcatominey Let us know if you can find time to keep working on this. There is definitely interest in alternate lock providers. Thanks!

**Comment by brikis98** [comment]
This has not made any progress in over 4 months, and as Terraform 0.9 supports locking natively, we are removing locking from Terragrunt in #167. Therefore, I'm going to close this PR.

**Comment by pmcatominey** [comment]
Sorry for the delay, once hashicorp/terraform#13036 is merged then Azure locking will be natively supported by Terraform.

**Comment by brikis98** [comment]
@pmcatominey Nice!

**Pull request closed without merging**
