### PR TITLE
Added support for gcs impersonate_service_account option available in terraform 0.14rc1

### PR DESCRIPTION
**Pull request by ksvladimir**
We just started using terragrunt and love the tool, thanks for building it!

Our environment relies on the [impersonate_service_account](https://github.com/hashicorp/terraform/blob/master/website/docs/backends/types/gcs.html.md#configuration-variables) option of the gcs state backend. It's available in terraform 0.14rc1, so terragrunt will soon need to support it. This PR adds this support.

### CODE REVIEW

**Comment by yorinasub17** [comment]
Thanks for the contribution! This makes sense to me. I'll kick off a build now.

**Review by yorinasub17 — APPROVED** [review]

**Review by robmorgan — APPROVED** [review]
It looks like the build passed in https://app.circleci.com/pipelines/github/gruntwork-io/terragrunt/512/workflows/e00cfb93-38eb-4e6e-8597-6bc461f31576 so I'm happy to accept this if we can build binaries successfully for all platforms.

**Comment by yorinasub17** [comment]
Thanks for the additional review! Will go forward with merging and releasing this.

**Review by eak12913 — APPROVED** [review]
Rubber stamp

**Pull request merged**
