### PR TITLE
Remove TERRAGRUNT_PROVIDER_CACHE_DISABLE_PARTIAL_LOCK_FILE reference

### PR DESCRIPTION
**Pull request by maonat**
## Description

* Removed reference for TERRAGRUNT_PROVIDER_CACHE_DISABLE_PARTIAL_LOCK_FILE as it's been removed since v0.58.3 release of terragrunt

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [ ] Run the relevant tests successfully, including pre-commit checks.
- [ ] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [ ] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

### CODE REVIEW

**Comment by maonat** [comment]
Because there is no documentation whatsoever on the new approach introduced in v0.58.3, is there anything to be done to have the same result in the newest versions? Or was this mistakenly removed from the application? I couldn't find any release notes about this change.

**Comment by levkohimins** [comment]
Hi @maonat, Thanks for your contribution!

**Review by levkohimins — APPROVED** [review]
LGTM!

**Comment by maonat** [comment]
@levkohimins is there a chance to know if the change to remove this was planned and the functionality to use the cached providers works without this parameter also using parallelism?
The PR where this was implemented is #3001 and as stated above in my comment, I couldn't find any release note about it.

**Review by levkohimins — CHANGES_REQUESTED** [review]
@maonat,
Could you please remove other mentions of `terragrunt-provider-cache-disable-partial-lock-file`? :

```
docs/_docs/04_reference/cli-options.md:78:6:  - [terragrunt-provider-cache-disable-partial-lock-file](#terragrunt-provider-cache-disable-partial-lock-file)
docs/_docs/04_reference/cli-options.md:78:60:  - [terragrunt-provider-cache-disable-partial-lock-file](#terragrunt-provider-cache-disable-partial-lock-file)
docs/_docs/04_reference/cli-options.md:746:6:  - [terragrunt-provider-cache-disable-partial-lock-file](#terragrunt-provider-cache-disable-partial-lock-file)
docs/_docs/04_reference/cli-options.md:746:60:  - [terragrunt-provider-cache-disable-partial-lock-file](#terragrunt-provider-cache-disable-partial-lock-file)
```

If I do this, I won't be able to approve this pull request.

**Comment by levkohimins** [comment]
> @levkohimins is there a chance to know if the change to remove this was planned and the functionality to use the cached providers works without this parameter also using parallelism? The PR where this was implemented is #3001 and as stated above in my comment, I couldn't find any release note about it.

We have removed `TERRAGRUNT_PROVIDER_CACHE_DISABLE_PARTIAL_LOCK_FILE` from the code as it became unnecessary after adding lock file generation #3089. Nothing else has changed, so using parallelism is still safe with cached providers.

**Comment by maonat** [comment]
> > @levkohimins is there a chance to know if the change to remove this was planned and the functionality to use the cached providers works without this parameter also using parallelism? The PR where this was implemented is #3001 and as stated above in my comment, I couldn't find any release note about it.
> 
> We have removed `TERRAGRUNT_PROVIDER_CACHE_DISABLE_PARTIAL_LOCK_FILE` from the code as it became unnecessary after adding lock file generation #3089. Nothing else has changed, so using parallelism is still safe with cached providers.

Okay found the merge #3055 
Thanks!

PS: Is there a way to get in contact with you directly on a slack? I saw that you have a slack for the community but allows only emails with gruntwork.io and empatica.com domain.
Thanks

**Comment by levkohimins** [comment]
> PS: Is there a way to get in contact with you directly on a slack? I saw that you have a slack for the community but allows only emails with gruntwork.io and empatica.com domain. Thanks

I can contact me using `@Levko/Gruntwork`  in Slack.

**Review by levkohimins — APPROVED** [review]
LGTM!

**Pull request merged**
