### PR TITLE
Fix nested dependency parsing

### LINKED ISSUE #2955: There is no variable named "dependency" - terragrunt 0.55.4
**Describe the bug**
With terragrunt 0.55.4 I get errors all over the place when using dependency outputs as inputs

**To Reproduce**
Have a dependency, reference an output of that dependency as an input, and probably have the dependency have dependencies also.

```hcl

dependency "eks_cluster" {
  config_path = "../../eks-cluster"
}

dependency "kms_key_2024" {
  config_path = "../../kms/external-pv-key-2024"
}

inputs = {
  provider_url           = dependency.eks_cluster.outputs.cluster_oidc_issuer_url
  cluster_id             = dependency.eks_cluster.outputs.cluster_name
  cluster_endpoint       = dependency.eks_cluster.outputs.cluster_endpoint
  cluster_ca_cert        = dependency.eks_cluster.outputs.cluster_certificate_authority_data
  oidc_provider_arn      = dependency.eks_cluster.outputs.oidc_provider_arn
  kms_keys_for_ebs_csi   = [dependency.kms_key_2024.outputs.arn]
}
```

When planning / applying I get errors from the referenced modules:

```
ERRO[0000] Error: Unknown variable
            
ERRO[0000]   on /some/path/to/infrastructure-live/test/eu-central-1/e2e2/services/eks-01/eks-cluster/terragrunt.hcl line 47: 
ERRO[0000]   47:   kms_key_for_node_ebs = dependency.external-ebs-key-2024.outputs.arn 
ERRO[0000]                                              
ERRO[0000] There is no variable named "dependency".
    
WARN[0000] Error reading partial config  for dependency eks_cluster: /some/path/to/infrastructure-live/test/eu-central-1/e2e2/services/eks-01/eks-cluster/terragrunt.hcl:47,26-36: Unknown variable; There is no variable named "dependency". 
ERRO[0000] Error: Unknown variable
            
ERRO[0000]   on /some/path/to/infrastructure-live/test/eu-central-1/e2e2/services/eks-01/kms/external-pv-key-2024/terragrunt.hcl line 44: 
ERRO[0000]   44:   ciphertrust_aws_kms_id = dependency.thales_kms.outputs.ciphertrust_aws_kms_id 
ERRO[0000]                                              
ERRO[0000] There is no variable named "dependency".
```

In those modules I have dependencies as well, as an example in that `eks-cluster/terragrunt.hcl` line 47:

```hcl
  kms_key_for_node_ebs = dependency.external-ebs-key-2024.outputs.arn
```

where the dependency is declared earlier as:
```hcl
dependency "external-ebs-key-2024" {
  config_path = "../kms/external-ebs-key-2024"
}
```

**Expected behavior**
No errors or warning should be thrown, as with terragrunt 0.55.3 and earlier

**Nice to have**
- [x] Terminal output

**Versions**
- Terragrunt version: 0.55.4
- Terraform version: 1.7.2
- Environment details (Ubuntu 20.04, Windows 10, etc.): macOS 14.3.1

**Additional context**
I am available on the Gruntwork Slack as `@Philipp`

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

Fixes #2955

### CODE REVIEW

**Review by denis256 — APPROVED** [review]

**Comment by levkohimins** [comment]
@denis256, thanks for the review.

**Comment by levkohimins** [comment]
Resolved in [v0.55.6](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.55.6) release.

**Comment by thrix** [comment]
@levkohimins @denis256 hi, sorry for the mention, but this change broke some workflows when there are transitive dependencies, see pls #3028.

**Comment by sergiojoker11** [comment]
Does one have to do something to use this feature? I am getting:
```
sj111@sergio:~/github-repos/terragrunt/clients/a-client/environments/pentest/components/mirror_maker$ tg init
INFO[0000] Terragrunt Cache server is listening on 127.0.0.1:42153 
INFO[0000] Start Terragrunt Cache server                
ERRO[0019] Error: Unsupported attribute
       
ERRO[0019]   on /home/sj11/github-repos/terragrunt/clients/a-client/environments/pentest/components/mirror_maker/dependency_inputs.hcl line 22: 
ERRO[0019]   22:     "${dependency.k8s.inputs.platform_name}": { 
ERRO[0019]                                              
ERRO[0019] This object does not have an attribute named "inputs".
 
ERRO[0019] Error: Error in function call
      
ERRO[0019]   on /home/sj11/github-repos/terragrunt/clients/a-client/environments/pentest/components/mirror_maker/terragrunt.hcl line 29, in locals: 
ERRO[0019]   29:   merged_inputs = read_terragrunt_config("./merged_inputs.hcl") 
ERRO[0019]                                              
ERRO[0019] Call to function "read_terragrunt_config" failed: /home/sj11/github-repos/terragrunt/clients/a-client/environments/pentest/components/mirror_maker/dependency_inputs.hcl:22,22-29: Unsupported attribute;
This object does not have an attribute named "inputs"..

```
The env was created prior to this feature, if that helps...

**Comment by levkohimins** [comment]
@sergiojoker11, please provide a configuration that reproduces this issue.

**Pull request merged**
