### PR TITLE
Add regression tests for checking hook behavior with xxx-all commands

### PR DESCRIPTION
**Pull request by yorinasub17**

### CODE REVIEW

**Review by brikis98 — COMMENTED** [review]
What's the context for this?

**Comment by yorinasub17** [comment]
@brikis98 this is a regression test for confirming that https://github.com/gruntwork-io/terragrunt/issues/1532 was not a bug in hook running behavior, but rather in logging.

**Review by brikis98 — APPROVED** [review]
Understood, thx!

**Comment by yorinasub17** [comment]
Thanks for review! Merging now.

**Review by Matausi29 — COMMENTED** [review]
[]()

**Pull request merged**
