### PR TITLE
feat: support discovery of symlinked modules

### LINKED ISSUE #1611: Symlinks in Terragrunt
Hi!

I have found that Terragrunt does not work with symlinks as expected. Or expected but just in a different way from Terraform.
For example, lets assume that we have such folders structure:
```
/aaa/bbb/ccc/cloudfront/development
/aaa/bbb/ccc/cloudfront/development/stage
/aaa/bbb/ccc/modules/cloudfront
~/cloudfront_development -> /aaa/bbb/ccc/cloudfront/development
```
Now, when I am trying to run `~/cloudfront_development$ terragrunt run-all plan` it fails with an error:
```
ERRO[0000] Could not find any subfolders with Terragrunt configuration files
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
But commands `~/cloudfront_development$ terragrunt plan` and `~/cloudfront_development/stage$ terragrunt plan` separatelly works fine.

When I have navigated to `/aaa/bbb/ccc/cloudfront/development` directly and then run `$ terragrunt run-all plan` then it worked.

Also, I was trying to get rid of Terraform modules declaration and to declare scripts sources in the Terragrunt configuration `terraform` block:
replace modules.tf
```
module "stage" {
  source                          = "../../../modules/cloudfront"
}
```
with terragrunt.hcl
```
terraform {
  source = "../../..//modules/cloudfront"
}
```
But `~/cloudfront_development/stage$ terragrunt plan` has also exited with error:
```
ERRO[0004] Hit multiple errors:
stat /home/modules: no such file or directory
ERRO[0004] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
As you can see, the Terraform is recognizing the source path correctly even when running its commands from the symlink location.

So is it an expected behavior with symlinks in Terragrunt?

### PR DESCRIPTION
**Pull request by rodrigorfk**
## Description

Fixes #1611.

This PR continues the work that was started by @aslafy-z in the staled #3101 PR as following:
- It adds a `WalkWithSymlinks` function to the `util` package, here is the reason for having it's own implementation in the Terragrunt codebase:
  -  the [facebookgo/symwalk](https://pkg.go.dev/github.com/facebookgo/symwalk) implementation is the closest one for Terragrunt's use case, however that library is archived and the license does not adhere to Terragrunt's rules, it also does not handle circular symlinks.
  - the [edwardrf/symwalk](https://github.com/edwardrf/symwalk) implementation does handle circular symlinks, but it does not allow walking the full logical folder structure, therefore the end result provided by it won't match the expectations of this issue.
  - It is also important to clarify the usage of the `edwardrf/symwalk` on the original implementation was working only because the usage of `helpers.CopyEnvironment` in the tests, was resolving copying and symlinks statically, and not really preserving it on the temporary env path, which defeats the purpose of test and does not mimic what terragrunt will be doing when running targeting a real directory with symlinks directly into it, this issue was addressed in my tests and a comment regarding to it was left in the codebase.
- The integration tests are also adding some tests regarding to `.terragrunt-cache` invalidation, which was one of the concerns added by @denis256 https://github.com/gruntwork-io/terragrunt/pull/3101#issuecomment-2313224375

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [ ] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added support for discovery of symlinked modules

### CODE REVIEW

**Comment by denis256** [comment]
```
1 test failed out of 1501
TestWalkWithCircularSymlinks
```

**Comment by rodrigorfk** [comment]
Thanks for the input @denis256, there was a minor issue in the func, regarding to circular links, that was producing different results on MacOS and Linux. It is now fixed and the lint strict issues were also addressed. Could you please run the tests again?

**Comment by yhakbar** [comment]
Minor spelling issue that we can ignore, but tests are passing.

```
./util/file.go:909: evalutate ==> evaluate
./util/file.go:922: evalutate ==> evaluate
```

I'll let @denis256 decide if we should approve and merge.

**Comment by rodrigorfk** [comment]
Thanks for running the tests @yhakbar.

More than happy fix the spelling issue if needed @denis256. Also a bit puzzled by the `strict_lint` failure. I ran `make run-strict-lint` locally and didn't get any pending issue. Could you please let me know what is the issue? Thanks in advance.

**Comment by denis256** [comment]
```
/util/file.go:909: evalutate ==> evaluate
./util/file.go:922: evalutate ==> evaluate
```

:detective:

**Comment by rodrigorfk** [comment]
@denis256, spelling issue fixed, both `codespell .` and `make run-strict-lint` succeeded at my end now:

image

**Comment by yhakbar** [comment]
Thanks, @rodrigorfk . We're testing some edge cases to make sure that nothing is awry before merging.

**Review by denis256 — APPROVED** [review]

**Pull request merged**
