### PR TITLE
Prevent `init` command from parallel running if plugin cache is used

### LINKED ISSUE #1087: Error installing provider "aws": chmod .terraform/plugins/darwin_amd64/terraform-provider-aws_v2.52.0_x4: no such file or directory.
I've got the following error when tried to launch `terragrunt plan-all --terragrunt-source-update --terragrunt-non-interactive --terragrunt-source /path/to/the/sources` on multiple modules at the same time:
`Error installing provider "aws": chmod .terraform/plugins/darwin_amd64/terraform-provider-aws_v2.52.0_x4: no such file or directory.`

The mentioned modules do have separated set of dependencies

Terraform v0.12.23
terragrunt version v0.23.0

### LINKED ISSUE #1212: Issues with *-all commands and terraform plugin cache directory
If I set `TF_PLUGIN_CACHE_DIR` to any directory and use any terragrunt `*-all` commands fail with `Could not satisfy plugin requirements` errors. My repro case bellow:

terragrunt.hcl:
```hcl
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    bucket  = "my-terraform-test-state-test"
    key     = "${path_relative_to_include()}/terraform.tfstate"
    region  = "us-west-2"
    encrypt = true
  }
}
```

a/terragrunt.hcl:
```hcl
terraform {
  source = "../example-tf-module"
}

include {
  path = find_in_parent_folders()
}
```

example-tf-module/main.tf
```hcl
data "aws_region" "current" {}

output "aws_region" {
  value = data.aws_region.current.name
}
```

then I create directories `b` through `m` and copy `a/terragrunt.hcl` to them. My final directory tree is:
```
.
├── a
│   └── terragrunt.hcl
├── b
│   └── terragrunt.hcl
├── c
│   └── terragrunt.hcl
├── d
│   └── terragrunt.hcl
├── e
│   └── terragrunt.hcl
├── example-tf-module
│   └── main.tf
├── f
│   └── terragrunt.hcl
├── g
│   └── terragrunt.hcl
├── h
│   └── terragrunt.hcl
├── i
│   └── terragrunt.hcl
├── j
│   └── terragrunt.hcl
├── k
│   └── terragrunt.hcl
├── l
│   └── terragrunt.hcl
├── m
│   └── terragrunt.hcl
└── terragrunt.hcl
```

If cd to any of the one letter directories `terragrunt validate` works fine. From the root dir, with both `TF_LOG` and `TG_LOG` set to debug, `terragrunt validate-all` will fail some of the modules. TF/TG log and TF/TG putput from failed modules:
```

[terragrunt] [/Users/pietro/tmp/i] 2020/06/05 15:50:40 Running command: terraform validate
2020/06/05 15:50:40 [INFO] Terraform version: 0.12.26
2020/06/05 15:50:40 [INFO] Go runtime version: go1.13.11
2020/06/05 15:50:40 [INFO] CLI args: []string{"/usr/local/bin/terraform", "validate"}
2020/06/05 15:50:40 [DEBUG] Attempting to open CLI config file: /Users/pietro_monteiro/.terraformrc
2020/06/05 15:50:40 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/06/05 15:50:40 [INFO] CLI command args: []string{"validate"}
2020/06/05 15:50:40 [DEBUG] checking for provider in "."
2020/06/05 15:50:40 [DEBUG] checking for provider in "/usr/local/bin"
2020/06/05 15:50:40 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2020/06/05 15:50:40 [DEBUG] found provider "terraform-provider-aws_v2.65.0_x4"
2020/06/05 15:50:40 [DEBUG] found valid plugin: "aws", "2.65.0", "/Users/pietro/tmp/i/.terragrunt-cache/6gc2TEE1zxjCqaeQgfJsqVbaD4E/DfnLP98YzbykP1vtM_BhaFk10FU/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.65.0_x4"
2020/06/05 15:50:40 [DEBUG] checking for provisioner in "."
2020/06/05 15:50:40 [DEBUG] checking for provisioner in "/usr/local/bin"
2020/06/05 15:50:40 [DEBUG] checking for provisioner in ".terraform/plugins/darwin_amd64"
2020/06/05 15:50:40 [TRACE] terraform.NewContext: starting
2020/06/05 15:50:40 [TRACE] terraform.NewContext: resolving provider version selections

Error: Could not satisfy plugin requirements


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".



Error: provider.aws: new or changed plugin executable


[terragrunt] [/Users/pietro/tmp/h] 2020/06/05 15:50:41 Module /Users/pietro/tmp/h has finished with an error: Hit multiple errors:
exit status 1

Error: Could not satisfy plugin requirements


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".



Error: provider.aws: new or changed plugin executable


[terragrunt] [/Users/pietro/tmp/i] 2020/06/05 15:50:41 Module /Users/pietro/tmp/i has finished with an error: Hit multiple errors:
exit status 1
```

Using `--terragrunt-parallelism 1` fixes this but it makes my real code super slow to validate/plan/apply. My workaround is to emulate `terragrunt init-all --terragrunt-parallelism 1` using bash to `terragrunt init` each module sequentially.

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

Prevent `terraform init` command from parallel running if the terraform plugin cache is used.

## Related issues

Fixes #1212
Fixes #1087 
Relates #2542

### CODE REVIEW

**Comment by lorengordon** [comment]
This is a very cool solution!

**Review by denis256 — APPROVED** [review]

**Comment by levkohimins** [comment]
@denis256 Thanks for the review!

**Comment by levkohimins** [comment]
> This is a very cool solution!

Thanks, I hope this PR solves the issue.

**Comment by atheiman** [comment]
@levkohimins  - is there a way to override this? I understand the limitations of the cache, but i still want my `terragrunt run-all init` command to run in parallel and use the cache. I have other protections in place that get around the problems of the cache, and I init > 100 terragrunt modules in my ci/cd pipeline. I need the init to run in parallel (~5 min) vs sequentially (>30 min).

**Comment by levkohimins** [comment]
@atheiman, Starting with [v0.56.4](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.56.4), in which we implemented [Terragrunt Provider Cache](https://terragrunt.gruntwork.io/docs/features/provider-cache/), this code has been removed, namely `init` commands run in parallel.

**Pull request merged**
