### PR TITLE
Redirect the output of `terraform remote config` to stderr

### PR DESCRIPTION
**Pull request by Bowbaq**
@brikis98 alternative solution to #109

### CODE REVIEW

**Comment by brikis98** [comment]
Thanks for the PR!

From a look at the code, it's not obvious why we're redirecting that output. The real reason is that we run `remote config` before running other commands, so instead of your `stdout` containing the text from the command you wanted, it also has all the `remote config` output. Perhaps a cleaner and more general way to express that is: 

1. Compare `terragruntOptions.TerraformCliArgs` and the `args` parameter of the `RunShellCommand` method and to redirect `stdout` to `stderr` when those two are not equal.
1. Add a comment explaining this

**Comment by Bowbaq** [comment]
@brikis98 took another crack at it

**Comment by brikis98** [comment]
LGTM, thanks!

**Comment by brikis98** [comment]
I just created a new release here: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.9.6. If the build passes, the new binaries should show up there in a few minutes.

**Pull request merged**
