### PR TITLE
go.mod: update go-cty-yaml; update yamldecode regressions

### PR DESCRIPTION
**Pull request by andreykaipov**
Fixes https://github.com/gruntwork-io/terragrunt/issues/1704

### CODE REVIEW

**Comment by yorinasub17** [comment]
Thanks for your contribution! However, I think the go mod file was botched somehow because I am getting the following compile error when I checkout this PR:

```
# github.com/gruntwork-io/terragrunt/test
../../../../../pkg/mod/go.mozilla.org/sops/v3@v3.7.0/hcvault/keysource.go:16:2: ambiguous import: found package github.com/hashicorp/vault/api in multiple modules:
        github.com/hashicorp/vault v0.10.4 (/Users/yoriy/go/pkg/mod/github.com/hashicorp/vault@v0.10.4/api)
        github.com/hashicorp/vault/api v1.0.5-0.20210210214158-405eced08457 (/Users/yoriy/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.5-0.20210210214158-405eced08457)
FAIL    github.com/gruntwork-io/terragrunt/test [setup failed]
```

Perhaps it's better to update the internal terraform version to latest, which is where we are getting the terraform defined helper functions from?

**Comment by andreykaipov** [comment]
That's weird. The `go.mod` file didn't run for me even before updating `go-cty-yaml` so I think it's something on my part...

> Perhaps it's better to update the internal terraform version to latest, which is where we are getting the terraform defined helper functions from?

Would that fix it? Reading through https://github.com/hashicorp/terraform/issues/23770, it looks like it was fixed in Terraform in v0.13, so I imagine the fix would have been included in Terragrunt by now.

**Comment by yorinasub17** [comment]
We don't update the internal link with terraform frequently, and only opt to update it as needed. So if you look at `go.mod`, you will see that we are linking in `v0.12.24`.

**Comment by andreykaipov** [comment]
Ah I see! I tried updating it to the latest v0.15.5 but I'm getting even stranger module import errors. I'm kind of worried what other implications that might have though.

I realized my mistake in the original commit though. I didn't realize y'all exclude the vendor directory so I shouldn't have tidied. Would you be okay with only a change to the underlying library?

**Comment by yorinasub17** [comment]
> I realized my mistake in the original commit though. I didn't realize y'all exclude the vendor directory so I shouldn't have tidied. Would you be okay with only a change to the underlying library?

That's fine! I just confirmed the updated go.mod works for me now, so we can move forward with this PR! I'll kick off the internal build, and if it passes, we can merge this in.

**Review by yorinasub17 — APPROVED** [review]

**Comment by yorinasub17** [comment]
Merged and released! Thanks for your contribution! https://github.com/gruntwork-io/terragrunt/releases/tag/v0.29.10

(binaries will show up shortly)

**Comment by andreykaipov** [comment]
Thank you so much! I really appreciate how quick the team cuts releases! 🙏

**Pull request merged**
