### PR TITLE
Found another cornercase

### PR DESCRIPTION
**Pull request by jocgir**
There was a bug in certain circumstance whit processSingleInterpolationInString.

The regex can consider multiple interpolations as only one. The main problem is that INTERPOLATION_SYNTAX_REGEX is too general. I did not change it to avoid undesired side effects. But I added a test in processSingleInterpolationInString to ensure that there is only one match between the quotes.

I also added a test that catch the misbehaviour.

Sorry for the inconvenience.

### CODE REVIEW

**Comment by jocgir** [comment]
It could work. I thought about that, but the problem with that kind of exclusion in regex is that it may have some undesired effect. Like that:
```
key = "${get_env("SOME_VAR", "SOME{VALUE}")}:
```

Which is doubtful, but perfectly valid.

**Comment by brikis98** [comment]
Ah, good point. Do we have a test case for that?

**Comment by jocgir** [comment]
Not yet.

I am trying something on regex101 to address this point

https://regex101.com/r/wG3aM3/302

I must say that in our forked terragrunt version, we made several «enhancements» that are not ready to be submitted as PR. One of these is direct support for ${var.whatever} in terragrunt config. It would be nice if we can have a talk regarding those.

**Comment by brikis98** [comment]
> I am trying something on regex101 to address this point https://regex101.com/r/MVuA1t/1

Heh, nice. That said, there are diminishing returns here. A small tweak to the regex to avoid extra if-statements is good, but if the fix requires a huge, hard-to-understand regex, then an if-statement is probably easier to maintain.

> One of them is direct support for ${var.whatever} in terragrunt config. It would be nice if we can have a talk regarding those.

Nice. We have a couple relevant discussions going on around this topic: 

https://github.com/gruntwork-io/terragrunt/issues/132
https://github.com/gruntwork-io/terragrunt/issues/147#issuecomment-282276693

**Comment by brikis98** [comment]
@jocgir Let me know if you found a reasonable regex to fix this. If not, happy to merge the if-statement once we add the test case mentioned above.

**Comment by jocgir** [comment]
Yes, I think it would be preferabable to improve the regex (bug segmenting it in smaller, more readable parts).

**Comment by brikis98** [comment]
New regex looks promising! That said, it seems to still do a greedy capture, so is the reason that it works because you are now matching on word characters (`\w`) so that `}` will no longer match? Does it work correctly with the test case you mentioned earlier?

```
key = "${get_env("SOME_VAR", "SOME{VALUE}")}:
```

**Comment by jocgir** [comment]
Hi, I just a a test to ensure it.

The \w+ just ensure that we got `some_function` in `${   some_function()   }`. We tolerate spaces around it, but not between the function name and the opening parenthesis. Just add tests for that too.

The tricky part is more in the parameters. There are still possible corner cases. Regex will never replace a real lexer/parser.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.12.19

**Pull request merged**
