### PR TITLE
Use STS to get user information to support using session tokens

### PR DESCRIPTION
**Pull request by ryangardner**
This is in reference to issue #21  

I've tested a build of this locally and it does acquire locks with session tokens

### CODE REVIEW

**Comment by ryangardner** [comment]
If the STS UserId from the `getCallerIdentity` call is not a 1:1 match for the username that came back from `iam.getUser`, some variables that are named "username" should probably be renamed for clarity purposes

**Comment by brikis98** [comment]
Fantastic, thanks! A few questions:

1. Do all the test pass? You can run them using `go test -v $(glide novendor)`. We've unfortunately had to disable the CircleCI job for PRs as our tests involve AWS creds (see [here for more info](https://circleci.com/docs/fork-pr-builds/)).
1. Is an IAM permission necessary for the `sts:GetCallerIdentity`?

**Comment by ryangardner** [comment]
An iam isn't necessary for `getCallerIdentity` as far as I can tell (there
is no checkbox to enable it in their policy builder tool, but they have one
for everything else. Others who were more involved with the changes to
terraform have said it doesn't require any iams)

I'll run all the tests in a little bit and confirm the work.

**Comment by ryangardner** [comment]
is the s3 bucket used by the tests supposed to be accessible to other accounts?  It is failing with a 403 on the s3 bucket - is there a way for me to set up an s3 bucket on my account that I can use to run the tests?

```
go test -v $(glide novendor)
=== RUN   TestTerragruntWorksWithLocalTerraformVersion
--- FAIL: TestTerragruntWorksWithLocalTerraformVersion (1.00s)
	integration_test.go:30: The S3 Bucket in the .terragrunt file does not exist. S3 Bucket Name = 'gruntwork-terragrunt-tests'. S3 Bucket Region = 'us-west-2'. Full Error Message = AccessDenied: Access Denied
			status code: 403, request id: 3D2637FBC18C2117
FAIL
exit status 1
FAIL	github.com/gruntwork-io/terragrunt/test	1.014s
```

**Comment by brikis98** [comment]
Ah, I think that may be a bad assumption in the tests. Instead, they should probably create the S3 bucket themselves. @josh-padnick Could you take a look?

**Comment by josh-padnick** [comment]
Yeah, to keep things simple, I just assumed the existence of an S3 bucket (naturally in our Gruntwork account), but @brikis98 is correct that it'd be better if the test creates its own S3 bucket. 

That update will involve generating a random name for the S3 bucket, creating it, interpolating the values into the `.terragrunt` file, and deleting the S3 bucket, so if you just want to get passing tests for now, you might change the values in the `const` and the `.terragrunt` file locally only for now, and I'll update these shortly, hopefully tonight or tomorrow.

**Comment by ryangardner** [comment]
I created a bucket and edited the .terragrunt file and and the test to point to the bucket and then the integration test passed.

For these tests I was using my STS credentials - I don't have any non-STS based credentials to test with at the moment. Earlier today I did have a set that I used to test that it still worked. 

One thing that does change from `iam getUser` vs `sts getCallerIdentiy` is that the caller identity returns the userId and not a username - it seems like this should be fine I think for what terragrunt uses it for (an identifier of which user has the lock) but it's worth noting that it is different

**Comment by brikis98** [comment]
Excellent, thanks! Merging now.

**Comment by ryangardner** [comment]
Thanks for the fast turnaround getting this merged!

**Pull request merged**
