### PR TITLE
Reference to dependency inputs

### LINKED ISSUE #2388: dependency: provide access to dependency inputs
When a dependency is specified, we can use the `outputs` of that dependency in the current module.

However, it would be "nice" to be able to use the `inputs` of that module as well. If we consider that we specify, perhaps, a date or time, or certain Tag values to the module, those values might not be represented in the module's outputs. However, a dependency may want to know those values -- so that something can be created with the same time interval, or with the same tags as the parent.

```
terraform {
  source = "email-notifications"
}
dependency "cluster" {
  config_path = "../cluster"
}

inputs {
  cluster_name = dependency.cluster.outputs.name

  addresses = [ for u in dependency.cluster.inputs.users : "${u}@mydomain.com" ]

  aws_tags = merge(dependency.cluster.inputs.aws_tags, { "module" = "email-notifications" })
}
```
in this case, "users" would be an input to "cluster" (probably authentication/permissions) and I would to set them up for e-mail notifications about the cluster in a separate module.

### PR DESCRIPTION
**Pull request by levkohimins**
## Description

This PR adds the ability to reference dependency inputs data. 

```hcl
dependency "test" {
  config_path = "../dependency"
}

inputs = {
  foo = dependency.test.inputs.foo
}
```

Fixes #2388

### CODE REVIEW

**Comment by denis256** [comment]
I suspect handling of includes with relative path is not working right:
```
$ terragrunt apply
WARN[0000] Error reading file /projects/gruntwork/terragrunt-tests/issue-2945/app/local.hcl: open /projects/gruntwork/terragrunt-tests/issue-2945/app/local.hcl: no such file or directory 
WARN[0000] Error reading partial config  for dependency test: open /projects/gruntwork/terragrunt-tests/issue-2945/app/local.hcl: no such file or directory 
ERRO[0000] Error: Unsupported attribute
       
ERRO[0000]   on /projects/gruntwork/terragrunt-tests/issue-2945/app/terragrunt.hcl line 6: 
ERRO[0000]    6:   data = dependency.test.inputs.foo 
ERRO[0000]                                              
ERRO[0000] This object does not have an attribute named "inputs".
 
ERRO[0000] /projects/gruntwork/terragrunt-tests/issue-2945/app/terragrunt.hcl:6,25-32: Unsupported attribute; This object does not have an attribute named "inputs". 
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1 

```
https://github.com/denis256/terragrunt-tests/tree/master/issue-2945

**Comment by levkohimins** [comment]
> I suspect handling of includes with relative path is not working right:
> 
> ```
> $ terragrunt apply
> WARN[0000] Error reading file /projects/gruntwork/terragrunt-tests/issue-2945/app/local.hcl: open /projects/gruntwork/terragrunt-tests/issue-2945/app/local.hcl: no such file or directory 
> WARN[0000] Error reading partial config  for dependency test: open /projects/gruntwork/terragrunt-tests/issue-2945/app/local.hcl: no such file or directory 
> ERRO[0000] Error: Unsupported attribute
>        
> ERRO[0000]   on /projects/gruntwork/terragrunt-tests/issue-2945/app/terragrunt.hcl line 6: 
> ERRO[0000]    6:   data = dependency.test.inputs.foo 
> ERRO[0000]                                              
> ERRO[0000] This object does not have an attribute named "inputs".
>  
> ERRO[0000] /projects/gruntwork/terragrunt-tests/issue-2945/app/terragrunt.hcl:6,25-32: Unsupported attribute; This object does not have an attribute named "inputs". 
> ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1 
> ```
> 
> https://github.com/denis256/terragrunt-tests/tree/master/issue-2945

Thank you, fixed.

**Review by denis256 — APPROVED** [review]

**Comment by levkohimins** [comment]
@denis256 thanks for the review.

**Comment by levkohimins** [comment]
Resolved [v0.55.4](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.55.4) release.

**Comment by kmentch** [comment]
I noticed that the documentation for this got lost somewhere, happy to open another issue or submit a PR to fix if necessary.

**Comment by yhakbar** [comment]
Hey @kmentch , that was intentional. We're removing support for reading dependency inputs in a future release of Terragrunt, and we want to avoid having users leverage that functionality. See the [strict control](https://terragrunt.gruntwork.io/docs/reference/strict-mode/#skip-dependencies-inputs).

Are you currently using dependency inputs? If so, could you share what use-case you have for them in a GitHub Discussion or Discord? I want to make sure we address your needs if removing dependency inputs support will impact you.

**Pull request merged**
