### PR TITLE
Bump AWS SDK to version v1.37.7 to support AWS SSO

### PR DESCRIPTION
**Pull request by z0mbix**
I've bumped the SDK version and ran `go mod tidy`. The only testing I've done is run `make build` and run a terragrunt plan/apply in a few modules, but seems to work as expected.

It relates to https://github.com/gruntwork-io/terragrunt/issues/1129

### CODE REVIEW

**Comment by thapabishwa** [comment]
Encountered following error.
```
Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): SSOProviderInvalidToken: the SSO session has expired or is invalid
caused by: expected RFC3339 timestamp: parsing time "2021-02-10T11:02:51UTC" as "2006-01-02T15:04:05Z07:00": cannot parse "UTC" as "Z07:00"
```

**Review by brikis98 — APPROVED** [review]
Thanks for the PR! I'll kick off tests now to see if it works with no other code changes.

That said, how do we know this now works with SSO? Are there no other changes needed to support that?

**Comment by z0mbix** [comment]
You need to login first with `aws sso login --profile something` as described here:

https://aws.amazon.com/blogs/developer/aws-sso-support-in-the-aws-sdk-for-go/

I've been using this build all day with no problems.

**Comment by z0mbix** [comment]
Also, there was an issue in the terraform repo where if you have a `credential_process` configured for getting the SSO credentials, then this can and probably will cause an error, so make sure you remove that.

**Review by thapabishwa — COMMENTED** [review]
I did use the sso command to begin with. And also removed the credential_process. Still have the issue.

```
~ >>> aws sso login --profile MyProfile
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.us-west-2.amazonaws.com/

Then enter the code:

<CODE-HERE>
Opening in existing browser session.
Successully logged into Start URL: https://<url>.awsapps.com/start#/
~ >>>  terragrunt apply  --terragrunt-tfpath terraform0.12
ERRO[0000] Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): SSOProviderInvalidToken: the SSO session has expired or is invalid
caused by: expected RFC3339 timestamp: parsing time "2021-02-11T13:53:59UTC" as "2006-01-02T15:04:05Z07:00": cannot parse "UTC" as "Z07:00" 
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1 
~>>> cat ~/.aws/config                                                                       
[profile MyProfile]
sso_start_url = https://<url>.awsapps.com/start#/
sso_region = us-west-2
sso_account_id = <account>
sso_role_name = <Role-Name>
region = us-east-2
output = json
```

**Comment by thapabishwa** [comment]
> I did use the sso command to begin with. And also removed the credential_process. Still have the issue.
> 
> ```
> ~ >>> aws sso login --profile MyProfile
> Attempting to automatically open the SSO authorization page in your default browser.
> If the browser does not open or you wish to use a different device to authorize this request, open the following URL:
> 
> https://device.sso.us-west-2.amazonaws.com/
> 
> Then enter the code:
> 
> <CODE-HERE>
> Opening in existing browser session.
> Successully logged into Start URL: https://<url>.awsapps.com/start#/
> ~ >>>  terragrunt apply  --terragrunt-tfpath terraform0.12
> ERRO[0000] Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): SSOProviderInvalidToken: the SSO session has expired or is invalid
> caused by: expected RFC3339 timestamp: parsing time "2021-02-11T13:53:59UTC" as "2006-01-02T15:04:05Z07:00": cannot parse "UTC" as "Z07:00" 
> ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1 
> ~>>> cat ~/.aws/config                                                                       
> [profile MyProfile]
> sso_start_url = https://<url>.awsapps.com/start#/
> sso_region = us-west-2
> sso_account_id = <account>
> sso_role_name = <Role-Name>
> region = us-east-2
> output = json
> ```

https://github.com/golang/go/issues/20555

**Comment by brikis98** [comment]
> You need to login first with `aws sso login --profile something` as described here:
> 
> https://aws.amazon.com/blogs/developer/aws-sso-support-in-the-aws-sdk-for-go/
> 
> I've been using this build all day with no problems.

Hm, a few questions:

1. That blog post you linked to says that we must enable `SharedConfigState: session.SharedConfigEnable` in the Go code. Do we need to do that in Terragrunt then?
2. How does `aws sso login` work if you need to switch across several accounts frequently? E.g., I want to run one command in dev, then another in stage, then back to dev, and so on. Do you only have one active login on your entire computer at a time? Or if you do `aws sso login --profile <foo>` and then `aws sso login --profile <bar>`, then you can actively use `foo` or `bar` profiles until those creds expire?

**Comment by z0mbix** [comment]
> > You need to login first with `aws sso login --profile something` as described here:
> > https://aws.amazon.com/blogs/developer/aws-sso-support-in-the-aws-sdk-for-go/
> > I've been using this build all day with no problems.
> 
> Hm, a few questions:
> 
> 1. That blog post you linked to says that we must enable `SharedConfigState: session.SharedConfigEnable` in the Go code. Do we need to do that in Terragrunt then?
> 2. How does `aws sso login` work if you need to switch across several accounts frequently? E.g., I want to run one command in dev, then another in stage, then back to dev, and so on. Do you only have one active login on your entire computer at a time? Or if you do `aws sso login --profile <foo>` and then `aws sso login --profile <bar>`, then you can actively use `foo` or `bar` profiles until those creds expire?

You only need to run `aws sso login` once, then you are authenticated against all profiles, so switching is as simple as setting the correct profile, so this kind of thing works:

```
$ aws sso login --nonprod
$ aws s3 ls --profile nonprod
$ aws s3 ls --profile prod
```

I don't believe any further changes are needed, but it's hard for me to test this change doesn't break current behaviour.

**Comment by brikis98** [comment]
> You only need to run `aws sso login` once, then you are authenticated against all profiles, 

Ohhh, interesting. So it must be getting some sort of temp creds from SSO that then allow it to assume any role you need?

> I don't believe any further changes are needed, but it's hard for me to test this change doesn't break current behaviour.

Hm, yea, it's tough. The only item I'm left scratching my head about is why the blog post recommends adding that `SharedConfigState: session.SharedConfigEnable` if it's not required? Does Terragrunt still work for you if you add that setting?

**Comment by sylr** [comment]
@z0mbix can you share how your `~/.aws/config` and `~/.aws/credentials` look like because I myself can't login in all the SSO accounts at once:

```
$ aws sso login
Missing the following required SSO configuration values: sso_start_url, sso_region, sso_role_name, sso_account_id. To make sure this profile is properly configured to use SSO, please run: aws configure sso
```

**Comment by z0mbix** [comment]
```
[profile nonprod]
region = eu-west-1
output = json
sso_start_url = https://company.awsapps.com/start
sso_region = eu-west-1
sso_account_id = 1111111111111
sso_role_name = NonProdAdmin

[profile prod]
region = eu-west-1
output = json
sso_start_url = https://company.awsapps.com/start
sso_region = eu-west-1
sso_account_id = 2222222222222
sso_role_name = ProdAdmin
```

I only need to run `aws sso login --profile nonprod` which gives me access to both accounts.

**Comment by karlpokus** [comment]
> Hm, yea, it's tough. The only item I'm left scratching my head about is why the blog post recommends adding that `SharedConfigState: session.SharedConfigEnable` if it's not required? Does Terragrunt still work for you if you add that setting?

I bumped the aws-sdk-go to v1.37.14 today to use sso credentials for a cli I'm making and I can only confirm that yes `SharedConfigState` is needed. I think `.aws/config` is actually called the shared config.

````
sess := session.Must(session.NewSessionWithOptions(session.Options{
		SharedConfigState: session.SharedConfigEnable,
		Profile:           <profile>,
	}))
````

**Comment by brikis98** [comment]
@z0mbix per @karlpokus' comment above, would you be up for updating the PR to set `SharedConfigState: session.SharedConfigEnable`?

**Comment by UrosCvijan** [comment]
When this is merged, does it mean that terragrunt will support SSO credentials from ~/.aws/config without any other modifications etc.. ? Main reason I am interested is cause I want to use my SSO credentials and to jump between accounts/profiles during the same terragrunt run.

**Comment by oscarmorasu** [comment]
That's correct @UrosCvijan , no more tricks or workarounds or external tools, the native SSO credentials in the GO SDK would take care of everything. All you have to do is log in with the `aws sso login` command, and have all your profiles for the different accounts setup in your ~/.aws/config file. The ~/.aws/credentials file would be empty

@z0mbix,

Is there a way we can help to wrap this up and get this PR merged?

**Comment by swordfish444** [comment]
As temporary workaround, I was able to do the following:

```sh
[profile my-profile]
sso_start_url = xxxxxxx
sso_region = us-west-2
sso_account_id = xxxxxxx
sso_role_name = Admin
region = us-west-2
output = json

[profile my-profile2]
region = us-west-2
output = json
credential_process = aws-sso-util credential-process --profile my-profile
```

Then set your environment variable `AWS_PROFILE` or `AWS_DEFAULT_PROFILE` to **my-profile2**.

**Comment by ryno75** [comment]
> @z0mbix per @karlpokus' comment above, would you be up for updating the PR to set `SharedConfigState: session.SharedConfigEnable`?

is this not already set here? https://github.com/gruntwork-io/terragrunt/blob/master/aws_helper/config.go#L54

**Comment by brikis98** [comment]
> > @z0mbix per @karlpokus' comment above, would you be up for updating the PR to set `SharedConfigState: session.SharedConfigEnable`?
> 
> is this not already set here? https://github.com/gruntwork-io/terragrunt/blob/master/aws_helper/config.go#L54

🤦  

Hahah, you're right! OK, merging this and releasing. Thank you @z0mbix!

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.9

**Pull request merged**
