### PR TITLE
cli_app.go: make MODULE_REGEX more accepting

### PR DESCRIPTION
**Pull request by tamsky**
I had a `*.tf` file with a declaration of:
```
modules    "modulename"
```
The extra spaces meant the `shouldDownloadModules` logic was incorrect.

### CODE REVIEW

**Comment by brikis98** [comment]
Ah, good catch! 

Could you update one of the fixtures in the [test folder](https://github.com/gruntwork-io/terragrunt/tree/master/test) with extra whitespace so the tests catch this in the future? This [hello-world fixture is probably a simple candidate](https://github.com/gruntwork-io/terragrunt/blob/master/test/fixture-download/hello-world/main.tf). 

1. Temporarily revert your code change.
1. Update that fixture with extra whitespace.
1. Run the tests and make sure they fail.
1. Put your fix back.
1. Rerun the tests to make sure they now pass. 

Please paste the test output here, as we can't run the CI job automatically for external pull requests due to [security concerns](https://circleci.com/docs/1.0/fork-pr-builds/).

Thanks!

**Comment by brikis98** [comment]
@tamsky Have you had a chance to update the test fixtures with a test for this?

**Comment by tamsky** [comment]
Thanks for the reminder.

It looks like we care about the TestRemoteDownload test:

Running in the `master` branch without my change:
```
# ( cd test && go test -v 2>&1 | grep TestRemoteDownload )
=== RUN   TestRemoteDownload
=== RUN   TestRemoteDownloadWithRelativePath
=== RUN   TestRemoteDownloadOverride
--- PASS: TestRemoteDownloadWithRelativePath (0.46s)
--- PASS: TestRemoteDownload (0.27s)
--- PASS: TestRemoteDownloadOverride (0.60s)
```

Tweaking the test source to use a `hello-world/main.tf` with some offending syntax: https://github.com/tamsky/terragrunt/commit/4957072152e5a124ee699487b539a32c70525531

I then needed to patch my local test to use the above version:
``` diff
diff --git a/test/fixture-download/remote/terraform.tfvars b/test/fixture-download/remote/terraform.tfvars
index fed57b0..0f65483 100644
--- a/test/fixture-download/remote/terraform.tfvars
+++ b/test/fixture-download/remote/terraform.tfvars
@@ -2,6 +2,6 @@ name = "World"
 
 terragrunt = {
   terraform {
-    source = "github.com/gruntwork-io/terragrunt.git//test/fixture-download/hello-world?ref=v0.9.9"
+    source = "github.com/tamsky/terragrunt.git//test/fixture-download/hello-world?ref=test-fix-MODULE_REGEX"
   }
-}
\ No newline at end of file
+}
```

With the above change, but without clearing the temp directory the test still passes... 

### NB: it looks like there's a cache busting issue in the current integration test setup.

```
# ( cd test && go test -v 2>&1 | grep TestRemoteDownload )
=== RUN   TestRemoteDownload
=== RUN   TestRemoteDownloadWithRelativePath
=== RUN   TestRemoteDownloadOverride
--- PASS: TestRemoteDownloadWithRelativePath (0.28s)
--- PASS: TestRemoteDownload (0.29s)
--- PASS: TestRemoteDownloadOverride (0.45s)

: mtamsky in //Users/mtamsky/src/go/src/github.com/gruntwork-io/terragrunt on master [!];
# rm -rf /var/folders/vg/[snip]/T/terragrunt*

: mtamsky in //Users/mtamsky/src/go/src/github.com/gruntwork-io/terragrunt on master [!];
# ( cd test && go test -v 2>&1 | grep TestRemoteDownload )
=== RUN   TestRemoteDownload
=== RUN   TestRemoteDownloadWithRelativePath
=== RUN   TestRemoteDownloadOverride
--- PASS: TestRemoteDownloadWithRelativePath (15.30s)
--- FAIL: TestRemoteDownload (15.98s)
--- PASS: TestRemoteDownloadOverride (22.75s)
```

So, `FAIL: TestRemoteDownload (15.98s)` is what we wanted.

Now, switching to my branch and repeating the above steps:
```
: mtamsky in //Users/mtamsky/src/go/src/github.com/gruntwork-io/terragrunt on master [!];
# git checkout fix/MODULE_REGEX
M       terragrunt
M       test/fixture-download/remote/terraform.tfvars
Switched to branch 'fix/MODULE_REGEX'

: mtamsky in //Users/mtamsky/src/go/src/github.com/gruntwork-io/terragrunt on fix/MODULE_REGEX [!];
# rm terragrunt
remove terragrunt? y

: mtamsky in //Users/mtamsky/src/go/src/github.com/gruntwork-io/terragrunt on fix/MODULE_REGEX [!];
# go build .

: mtamsky in //Users/mtamsky/src/go/src/github.com/gruntwork-io/terragrunt on fix/MODULE_REGEX [!];
# rm -rf /var/folders/vg/[snip]/T/terragrunt*

: mtamsky in //Users/mtamsky/src/go/src/github.com/gruntwork-io/terragrunt on fix/MODULE_REGEX [!];
# ( cd test && go test -v 2>&1 | grep TestRemoteDownload )
=== RUN   TestRemoteDownload
=== RUN   TestRemoteDownloadWithRelativePath
=== RUN   TestRemoteDownloadOverride
--- PASS: TestRemoteDownloadOverride (19.48s)
--- PASS: TestRemoteDownloadWithRelativePath (25.09s)
--- PASS: TestRemoteDownload (37.41s)
```

**Comment by tamsky** [comment]
1. Do you want the changes in https://github.com/tamsky/terragrunt/commit/4957072152e5a124ee699487b539a32c70525531 
to be included in this PR?

2. What changes are desired in `test/fixture-download/remote/terraform.tfvars` to reflect the new `ref=` that will be needed?

**Comment by brikis98** [comment]
> Do you want the changes in tamsky@4957072 to be included in this PR?

Yes please!

> What changes are desired in test/fixture-download/remote/terraform.tfvars to reflect the new ref= that will be needed?

I'm not sure that we need a new `ref=`. Changing it got the test to fail for you, but not because the newly downloaded code did anything different, but simply that there *was* new code to download. Terragrunt only runs `get` if no modules have been downloaded at all. If you had run the tests previously, then those modules had already been downloaded. 

Probably the proper fix is to copy the fixture folders to a different temp folder each time. IIRC, the `copyEnvironment` function does just that, so we probably need to use it in all tests. That said, that's probably a separate bug, and can be handled in a separate PR.

**Comment by tamsky** [comment]
Changes to `test/fixture-download/remote/terraform.tfvars` are now included.

**Comment by brikis98** [comment]
Great, thx!

**Pull request merged**
