### PR TITLE
configuring session's credentials in getAWSAccountId() when assuming …

### PR DESCRIPTION
**Pull request by ebarault**
…a role

as discussed in https://github.com/gruntwork-io/terragrunt/issues/379

That would probably be as simple as this.
I tested on my current project, it works.

### CODE REVIEW

**Comment by brikis98** [comment]
Nice, thank you! 

Could you run the tests and post the log output? Due to security reasons, we unfortunately can't run tests automatically for external PRs.

**Comment by ebarault** [comment]
Here you are :
[test_results.txt](https://github.com/gruntwork-io/terragrunt/files/1500060/test_results.txt)

**Comment by brikis98** [comment]
OK, there's one test failure in there, but that seems to be a timeout calling DynamoDB, which is probably just an intermittent issue. Merging now. Thanks!

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.13.21

**Comment by ebarault** [comment]
Is there anything to do to make this new release available with `brew`?

**Comment by brikis98** [comment]
It happens automatically: https://github.com/Homebrew/homebrew-core/commit/8f5f97a137b6c7fe6f326e4ddf40e1ce93914fd9#diff-e533973dd2b8594e912a57ff81f37b95

**Pull request merged**
