### PR TITLE
Updated Makefile to generate mocks before build

### LINKED ISSUE #3125: Go vendoring broken in 0.58.3: no required module provides package github.com/gruntwork-io/terragrunt/terraform/getproviders/mocks
Preparing the vendored dependencies for the openSUSE package results in this error in 0.58.3:

```
INFO:obs-service-go_modules:Archive autodetected at /home/Buildservice/Branches/Branch_terraform/terragrunt/terragrunt-0.58.3.obscpio
INFO:obs-service-go_modules:Using archive terragrunt-0.58.3.obscpio
INFO:obs-service-go_modules:Extracting terragrunt-0.58.3.obscpio to /tmp/tmptd09ozuq
INFO:obs-service-go_modules:Switching to /tmp/tmptd09ozuq
INFO:obs-service-go_modules:Detected basename terragrunt-0.58.3 from archive
INFO:obs-service-go_modules:Using go.mod found at /tmp/tmptd09ozuq/terragrunt-0.58.3/go.mod
INFO:obs-service-go_modules:go mod download
INFO:obs-service-go_modules:go mod vendor
ERROR:obs-service-go_modules:go: github.com/gruntwork-io/terragrunt/terraform/getproviders tested by
        github.com/gruntwork-io/terragrunt/terraform/getproviders.test imports
        github.com/gruntwork-io/terragrunt/terraform/getproviders/mocks: no required module provides package github.com/gruntwork-io/terragrunt/terraform/getproviders/mocks; to add it:
        go get github.com/gruntwork-io/terragrunt/terraform/getproviders/mocks
ERROR:obs-service-go_modules:go mod vendor failed
Aborting: service call failed:  /usr/lib/obs/service/go_modules --outdir /home/Buildservice/Branches/Branch_terraform/terragrunt/tmpwhmdhhs_.go_modules.service
```

### PR DESCRIPTION
**Pull request by denis256**
## Description

Updated Makefile to generate mocks before build

Fixes #3125.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

Updated Makefile to generate mocks before build.

### CODE REVIEW

**Comment by johanneskastl** [comment]
Thanks for taking care. Any idea how I can build terragrunt offline with this change, with only the vendored dependencies available?

Especially as the vendoring breaks due to the mocks being missing?

**Comment by denis256** [comment]
```
$ docker run -it --entrypoint /bin/bash  golang:1.21.8
root@fd3fe92b392b:/go# cd /go/src
root@fd3fe92b392b:/go/src# git clone https://github.com/gruntwork-io/terragrunt.git .
Cloning into '.'...
remote: Enumerating objects: 21319, done.
remote: Counting objects: 100% (3120/3120), done.
remote: Compressing objects: 100% (1076/1076), done.
remote: Total 21319 (delta 2068), reused 2798 (delta 1863), pack-reused 18199
Receiving objects: 100% (21319/21319), 29.27 MiB | 12.79 MiB/s, done.
Resolving deltas: 100% (13228/13228), done.
root@fd3fe92b392b:/go/src# go install github.com/vektra/mockery/v2@v2.36.0
root@fd3fe92b392b:/go/src# go generate ./...
root@fd3fe92b392b:/go/src# go mod download
root@fd3fe92b392b:/go/src# go mod vendor
root@fd3fe92b392b:/go/src# go build
root@fd3fe92b392b:/go/src# ls -lahrt terragrunt 
-rwxr-xr-x 1 root root 74M May  9 17:24 terragrunt
root@fd3fe92b392b:/go/src# 

```
For full "offline" image most probably you need to build base image with all dependencies and `mockery` too

**Comment by johanneskastl** [comment]
This workflow unfortunately means we cannot build terragrunt for openSUSE anymore. At least not without jumping through hoops, as the automation cannot run commands before preparing the vendor tarball.

I am not a Golang expert, but why can't mockery simply be added to the go.mod file and can be vendored like the other dependencies?

**Review by levkohimins — APPROVED** [review]
LGTM!

**Comment by denis256** [comment]
`mockery` should be installed as executable and mocks generated otherwise build will fail

**Pull request merged**
