### PR TITLE
Open Telemetry update

### PR DESCRIPTION
**Pull request by denis256**
## Description

Included changes:
 * Upgraded OpenTelmetry to v1.28.0 for upcoming Sops version upgrade
 * Fixed typo in env variable name `TELEMERTY` -> `TELEMETRY` 
```
TERRAGRUNT_TELEMERTY_TRACE_EXPORTER_HTTP_ENDPOINT -> TERRAGRUNT_TELEMETRY_TRACE_EXPORTER_HTTP_ENDPOINT

TERRAGRUNT_TELEMERTY_TRACE_EXPORTER_INSECURE_ENDPOINT -> TERRAGRUNT_TELEMETRY_TRACE_EXPORTER_INSECURE_ENDPOINT

TERRAGRUNT_TELEMERTY_METRIC_EXPORTER_INSECURE_ENDPOINT -> TERRAGRUNT_TELEMETRY_METRIC_EXPORTER_INSECURE_ENDPOINT
```

 * Old variables, if defined, will be used by Terragrunt, will be printed deprecated warning

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Added / Removed / Updated [X].

Updated OpenTelemetry: Upgraded to version v1.28.0.
Fixed Typo: Corrected typographical errors in telemetry environment variable names.

### CODE REVIEW

**Review by yhakbar — DISMISSED** [review]
Make sure to call out this breaking change in the release notes!

**Comment by denis256** [comment]
Old variables are still working, so it is not a breaking change yet

**Comment by yhakbar** [comment]
Well, I guess this is the kind of thing we would call out as something that will break in the future. 

I don't see any warnings introduced for users using the old env vars, but there should be some signal for users upgrading to this version that they will need to update their configs eventually.

**Comment by denis256** [comment]
Added warning printing in case if a deprecated variable is used:

image

**Review by yhakbar — APPROVED** [review]

**Pull request merged**
