### PR TITLE
terragrunt should copy .terraform.lock.hcl on `providers lock` command

### LINKED ISSUE #1500: Terragrunt doesn't save .terraform.lock.hcl from `providers lock`
When terragrunt configs may be applied from different platforms, you can see spurious updates to lock files after they have been checked in. To remedy this, you can use the `terraform providers lock` command to target all platforms you support https://www.terraform.io/docs/commands/providers/lock.html#specifying-target-platforms

Currently, terragrunt does not copy the `.terraform.lock.hcl` file when you run `terragrunt providers lock ...`

### PR DESCRIPTION
**Pull request by ZymoticB**
Fixes #1500

### CODE REVIEW

**Review by brikis98 — COMMENTED** [review]
Thanks for the PR! One thing that isn't clear to me is why this wasn't handled by [auto init](https://terragrunt.gruntwork.io/docs/features/auto-init/)? Had you run `init` before, and then updated to a new version of Terraform? If so, and you already had a `.terraform` folder, then I guess Terragrunt would not have run `init` automatically, and therefore, wouldn't have copied the lock file. 

Could you try Terragrunt _without_ this fix, but delete any `.terragrunt-cache`/`.terraform` folder first?

**Comment by ZymoticB** [comment]
> Thanks for the PR! One thing that isn't clear to me is why this wasn't handled by [auto init](https://terragrunt.gruntwork.io/docs/features/auto-init/)? Had you run `init` before, and then updated to a new version of Terraform? If so, and you already had a `.terraform` folder, then I guess Terragrunt would not have run `init` automatically, and therefore, wouldn't have copied the lock file.
> 
> Could you try Terragrunt _without_ this fix, but delete any `.terragrunt-cache`/`.terraform` folder first?

This change is to explicitly support the flow described here https://www.terraform.io/docs/commands/providers/lock.html#specifying-target-platforms.

`terraform init` is not guaranteed to pull all checksums depending on platforms, if you already have the provider requested in a cache, or if you are using a mirror. There are lots of details here https://github.com/hashicorp/terraform/issues/27264#issuecomment-743389837. This extra sub command enables you to ensure that the lock file is fully populated.

**Comment by brikis98** [comment]
> > Thanks for the PR! One thing that isn't clear to me is why this wasn't handled by [auto init](https://terragrunt.gruntwork.io/docs/features/auto-init/)? Had you run `init` before, and then updated to a new version of Terraform? If so, and you already had a `.terraform` folder, then I guess Terragrunt would not have run `init` automatically, and therefore, wouldn't have copied the lock file.
> > Could you try Terragrunt _without_ this fix, but delete any `.terragrunt-cache`/`.terraform` folder first?
> 
> This change is to explicitly support the flow described here https://www.terraform.io/docs/commands/providers/lock.html#specifying-target-platforms.
> 
> `terraform init` is not guaranteed to pull all checksums depending on platforms, if you already have the provider requested in a cache, or if you are using a mirror. There are lots of details here [hashicorp/terraform#27264 (comment)](https://github.com/hashicorp/terraform/issues/27264#issuecomment-743389837). This extra sub command enables you to ensure that the lock file is fully populated.

Ohhh, I get it, thanks for the context! Could you add that to the comment above `shouldCopyLockFile` so future maintainers can see the context too?

**Comment by ZymoticB** [comment]
I've updated, feel free to use the Github suggested edit stuff to make any small changes you'd like to see and commit them yourself.

**Review by brikis98 — APPROVED** [review]
Thanks! I'll kick off tests now.

**Comment by brikis98** [comment]
Tests passed! Merging now.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.27.3

**Pull request merged**
