### PR TITLE
Fix formatting bug in aws-provider-patch

### PR DESCRIPTION
**Pull request by yorinasub17**
The code that is outputted by `aws-provider-patch` formats complex expressions in a way that causes a syntax error in terraform. Specifically, it was formatting the following:

**before**
```
resource "null_resource" "complex_expression" {
  triggers = (
    var.secondary_aws_region == "us-east-1"
    ? { default = "True" }
    : {}
  )
}
```

**after**
```
resource "null_resource" "complex_expression" {
  triggers = (
    var.secondary_aws_region == "us-east-1"
    ? { default = "True" }
    : {}

) }
```

leading to the error

```
Error: Missing newline after argument

  on .terraform/modules/example_module/test/fixture-aws-provider-patch/example-module/main.tf line 33, in resource "null_resource" "complex_expression":
  28:   triggers = (
  29:     var.secondary_aws_region == "us-east-1"
  30:     ? { default = "True" }
  31:     : {}
  33: ) }
```

This PR fixes that by bumping the hcl library version.

### CODE REVIEW

**Review by brikis98 — APPROVED** [review]
LGTM!

**Comment by yorinasub17** [comment]
Thanks for review! Merging and releasing now!

**Comment by brikis98** [comment]
@yorinasub17 I think the release build for this PR failed. As a result, the binaries didn't get published, so now other builds that depend on them are failing. Would you mind taking a look?

**Comment by yorinasub17** [comment]
> I think the release build for this PR failed. As a result, the binaries didn't get published, so now other builds that depend on them are failing. Would you mind taking a look?

Fixed! I manually did the deploy steps to do the binaries, due to an unrecoverable failure in the deploy step: https://github.com/gruntwork-io/terragrunt/pull/1521

**Comment by brikis98** [comment]
Thank you Yori!

**Pull request merged**
